//! Golden-fixture test for the ODIM_H5 decoder.
//!
//! Fixture provenance: `tests/data/odim_pvol_synth.h5` is SYNTHETIC,
//! generated by `tests/data/gen_odim_fixture.py` with h5py 3.15.1 (libver
//! "earliest": superblock v0, v1 object headers, old-style groups) following
//! ODIM_H5 v2.2 (Michelson et al., EUMETNET OPERA WD_2008_03). The values
//! are deterministic ramps so every assertion below is computable by hand:
//! DBZH raw = (ray + bin) % 254 + 1 (gain 0.5, offset −32, gzip-chunked);
//! VRADH raw = (ray·2 + bin) % 254 + 1 (gain 0.1875, offset −24, contiguous).

use chrono::{TimeZone, Utc};
use recast_radar_core::model::{FieldName, Gate, RangeCoord, SweepMode};

const FIXTURE: &[u8] = include_bytes!("data/odim_pvol_synth.h5");

#[test]
fn decodes_synthetic_odim_pvol() {
    assert!(recast_radar_io_odim::odim::looks_like_hdf5_bytes(FIXTURE));
    let volume =
        recast_radar_io_odim::odim::read_odim_h5_volume(FIXTURE).expect("decode ODIM fixture");

    // /what + /where metadata.
    assert_eq!(volume.attrs.instrument_name, "TEST");
    assert_eq!(volume.attrs.site_name.as_deref(), Some("Synthetic"));
    assert_eq!(volume.location.latitude_deg, Some(39.74));
    assert_eq!(volume.location.longitude_deg, Some(-103.2927));
    assert_eq!(volume.location.altitude_m, Some(1519.0));
    assert_eq!(
        volume.time_reference,
        Utc.with_ymd_and_hms(2026, 6, 9, 5, 51, 0).unwrap()
    );
    assert_eq!(volume.provenance.decode.decoded_ray_count, 72);

    // Two elevation sweeps, ascending.
    assert_eq!(volume.sweeps.len(), 2);
    assert_eq!(volume.sweeps[0].fixed_angle_deg, 0.5);
    assert_eq!(volume.sweeps[1].fixed_angle_deg, 1.5);
    assert_eq!(volume.sweeps[0].sweep_mode, SweepMode::AzimuthSurveillance);

    let sweep = &volume.sweeps[0];
    assert_eq!(sweep.nrays(), 36);
    // Rays are north-relative scan-order bins: ray 0 centred at 5°.
    assert_eq!(sweep.rays.azimuth_deg[0], 5.0);
    assert_eq!(sweep.rays.azimuth_deg[9], 95.0);
    // rstart 0.05 km + rscale 150 m × 25 bins (centres from 125 m);
    // how/NI = 48 m/s.
    assert_eq!(
        sweep.range,
        RangeCoord::Uniform {
            first_center_m: 125.0,
            spacing_m: 150.0,
            ngates: 25,
        }
    );
    assert_eq!(
        sweep.ray_vars.nyquist_velocity_mps.as_ref().expect("NI")[0],
        48.0
    );

    // DBZH (gzip-chunked u8): physical = 0.5·raw − 32.
    let dbzh = sweep.field(&FieldName::Dbzh).expect("DBZH");
    assert_eq!(dbzh.gate(0, 0), Some(Gate::Missing)); // forced nodata (255)
    assert_eq!(dbzh.gate(0, 1), Some(Gate::Undetect)); // forced undetect (0)
    assert_eq!(dbzh.value(0, 2), Some(0.5 * 3.0 - 32.0)); // raw 3
    assert_eq!(dbzh.value(10, 4), Some(0.5 * 15.0 - 32.0)); // raw 15
    assert_eq!(dbzh.value(35, 24), Some(0.5 * 60.0 - 32.0)); // raw 60

    // VRADH (contiguous u8): physical = 0.1875·raw − 24.
    let vradh = sweep.field(&FieldName::Vradh).expect("VRADH");
    assert_eq!(vradh.value(2, 3), Some(0.1875 * 8.0 - 24.0)); // raw 8
    assert_eq!(vradh.value(0, 0), Some(0.1875 * 1.0 - 24.0)); // raw 1

    // Second sweep left its (0,0) untouched: DBZH raw 1 → −31.5 dBZ.
    let upper = volume.sweeps[1].field(&FieldName::Dbzh).unwrap();
    assert_eq!(upper.value(0, 0), Some(0.5 * 1.0 - 32.0));
}

#[test]
fn non_odim_hdf5_is_rejected_with_guidance() {
    // Corrupt the /what object attribute lookup by handing the decoder a
    // valid-but-non-ODIM HDF5: easiest is to check the error path through a
    // truncated buffer that still carries the signature.
    let err = recast_radar_io_odim::odim::read_odim_h5_volume(&FIXTURE[..512]).unwrap_err();
    let message = err.to_string();
    assert!(!message.is_empty());
}
