[package]
name = "recast-radar-io-nexrad"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bzip2.workspace = true
chrono.workspace = true
flate2.workspace = true
recast-radar-core = { path = "../recast-radar-core" }
rayon.workspace = true
thiserror.workspace = true

[dev-dependencies]
recast-radar-testdata = { path = "../recast-radar-testdata" }

[lints]
workspace = true
