//! BUFR tables B (elements) and D (sequences): the WMO master tables and
//! Meteo-France's local tables, embedded (`tables/`, generated by
//! `tools/bufr_tables.py`).
//!
//! The WMO tables are the latest edition 4 release (wmo-im/BUFR4, MIT):
//! master table entries keep their definitions across versions, so the
//! latest serves every version. A centre's local tables add (and may
//! redefine) entries; the local table of the message's centre and version
//! applies on top of the master table.

use std::collections::HashMap;
use std::sync::OnceLock;

/// How an element's bits are read.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ElementKind {
    /// A number: `(raw + reference) / 10^scale`.
    Numeric,
    /// A code or flag table entry (operators 2-01 to 2-03 do not apply).
    Code,
    /// CCITT IA5 characters, 8 bits each.
    Text,
}

/// A Table B entry.
#[derive(Clone, Copy, Debug)]
pub struct Element {
    /// Decimal scale.
    pub scale: i32,
    /// Reference value.
    pub reference: i64,
    /// Data width in bits.
    pub width: u32,
    /// How the bits are read.
    pub kind: ElementKind,
    /// The table's name for the element.
    pub name: &'static str,
    /// The table's unit.
    pub unit: &'static str,
}

/// The tables one message is decoded with.
#[derive(Debug, Default)]
pub struct Tables {
    elements: HashMap<u32, Element>,
    sequences: HashMap<u32, Vec<u32>>,
}

impl Tables {
    /// Table B entry `descriptor`.
    pub fn element(&self, descriptor: u32) -> Option<&Element> {
        self.elements.get(&descriptor)
    }

    /// Table D entry `descriptor`.
    pub fn sequence(&self, descriptor: u32) -> Option<&[u32]> {
        self.sequences.get(&descriptor).map(Vec::as_slice)
    }

    /// The tables for a message of `centre` with `local_version`: the WMO
    /// master tables, with Meteo-France's local tables (version 11, or 12
    /// for version 12 and later) for centre 85.
    pub fn for_message(centre: u16, local_version: u8) -> &'static Tables {
        static WMO: OnceLock<Tables> = OnceLock::new();
        static MF11: OnceLock<Tables> = OnceLock::new();
        static MF12: OnceLock<Tables> = OnceLock::new();
        let wmo = || build(&[(WMO_B, WMO_D)]);
        match (centre, local_version) {
            (85, 0) => WMO.get_or_init(wmo),
            (85, 1..=11) => MF11.get_or_init(|| build(&[(WMO_B, WMO_D), (MF11_B, MF11_D)])),
            (85, _) => MF12.get_or_init(|| build(&[(WMO_B, WMO_D), (MF12_B, MF12_D)])),
            _ => WMO.get_or_init(wmo),
        }
    }
}

const WMO_B: &str = include_str!("../tables/wmo_b.tsv");
const WMO_D: &str = include_str!("../tables/wmo_d.tsv");
const MF11_B: &str = include_str!("../tables/meteofrance_v11_b.tsv");
const MF11_D: &str = include_str!("../tables/meteofrance_v11_d.tsv");
const MF12_B: &str = include_str!("../tables/meteofrance_v12_b.tsv");
const MF12_D: &str = include_str!("../tables/meteofrance_v12_d.tsv");

/// Build tables from (B, D) pairs, later pairs overriding earlier ones.
fn build(layers: &[(&'static str, &'static str)]) -> Tables {
    let mut tables = Tables::default();
    for (b, d) in layers {
        for line in b.lines() {
            if let Some((descriptor, element)) = parse_element(line) {
                tables.elements.insert(descriptor, element);
            }
        }
        for line in d.lines() {
            let mut parts = line.split('\t');
            let (Some(head), Some(members)) = (parts.next(), parts.next()) else {
                continue;
            };
            let Ok(head) = head.trim().parse::<u32>() else {
                continue;
            };
            let members: Option<Vec<u32>> = members
                .split_whitespace()
                .map(|member| member.parse().ok())
                .collect();
            if let Some(members) = members {
                tables.sequences.insert(head, members);
            }
        }
    }
    tables
}

fn parse_element(line: &'static str) -> Option<(u32, Element)> {
    let mut parts = line.split('\t');
    let descriptor = parts.next()?.trim().parse().ok()?;
    let scale = parts.next()?.trim().parse().ok()?;
    let reference = parts.next()?.trim().parse().ok()?;
    let width = parts.next()?.trim().parse().ok()?;
    let unit = parts.next()?.trim();
    let name = parts.next().unwrap_or_default().trim();
    let lower = unit.to_ascii_lowercase();
    let kind = if lower.starts_with("ccitt") {
        ElementKind::Text
    } else if lower.contains("code table") || lower.contains("flag table") {
        ElementKind::Code
    } else {
        ElementKind::Numeric
    };
    Some((
        descriptor,
        Element {
            scale,
            reference,
            width,
            kind,
            name,
            unit,
        },
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn master_and_local_entries_resolve() {
        let tables = Tables::for_message(85, 12);
        let latitude = tables.element(5001).unwrap();
        assert_eq!(
            (latitude.scale, latitude.reference, latitude.width),
            (5, -9_000_000, 25)
        );
        assert_eq!(tables.element(1015).unwrap().kind, ElementKind::Text);
        // Meteo-France's local "extended delayed replication factor".
        assert_eq!(tables.element(31192).unwrap().width, 32);
        assert_eq!(
            tables.sequence(321193).unwrap(),
            &[105000, 31002, 201132, 30001, 201000, 21216, 21216]
        );
        assert_eq!(tables.sequence(301011).unwrap(), &[4001, 4002, 4003]);
        // Version 12 adds the radial velocity scaling 049241.
        assert!(tables.element(49241).is_some());
        assert!(Tables::for_message(85, 11).element(49241).is_none());
        assert!(Tables::for_message(98, 0).element(49241).is_none());
    }
}
