[package]
name = "recast-radar-correct"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
rayon.workspace = true
recast-radar-core = { path = "../recast-radar-core" }

[dev-dependencies]
image.workspace = true
recast-radar-io-nexrad = { path = "../recast-radar-io-nexrad" }

[lints]
workspace = true
