[package]
name = "recast-radar-correct"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
rayon.workspace = true
recast-radar-core = { path = "../recast-radar-core" }

[dev-dependencies]
image.workspace = true
recast-radar-io-jma = { path = "../recast-radar-io-jma" }
recast-radar-io-nexrad = { path = "../recast-radar-io-nexrad" }
recast-radar-testdata = { path = "../recast-radar-testdata" }
serde_json.workspace = true

[lints]
workspace = true
