"""Type stubs for the extension module ``recast_radar._native`` (Rust,
``crates/recast-radar-py/src``). Public names are re-exported by
``recast_radar``."""

import datetime
import os
from typing import Any, Union

Source = Union[str, os.PathLike[str], bytes, bytearray, memoryview]

__version__: str
NET: bool

class DecodeError(ValueError): ...
class UnavailableError(NotImplementedError): ...
class UnrepresentableError(ValueError): ...
class FetchError(OSError): ...

class Volume:
    """A decoded radar volume held in Rust (see ``recast_radar.read``)."""

    @property
    def source_format(self) -> str: ...
    @property
    def format_name(self) -> str: ...
    @property
    def label(self) -> str | None: ...
    @property
    def instrument_name(self) -> str: ...
    @property
    def time_reference(self) -> datetime.datetime: ...
    @property
    def time_coverage(self) -> tuple[datetime.datetime, datetime.datetime] | None: ...
    @property
    def latitude(self) -> float | None: ...
    @property
    def longitude(self) -> float | None: ...
    @property
    def altitude(self) -> float | None: ...
    @property
    def scan_name(self) -> str | None: ...
    @property
    def vcp(self) -> int | None: ...
    @property
    def nsweeps(self) -> int: ...
    @property
    def sweeps(self) -> list[dict[str, Any]]: ...
    @property
    def field_names(self) -> list[str]: ...
    @property
    def has_level2_metadata(self) -> bool: ...
    @property
    def format_metadata(self) -> dict[str, Any] | None: ...
    def to_datatree(self, **options: Any) -> Any: ...
    def to_pyart(self, **options: Any) -> Any: ...
    def write(self, path: str | os.PathLike[str], format: str, **options: Any) -> Any: ...
    def to_bytes(self, format: str, **options: Any) -> bytes: ...
    def publish(self, root: str | os.PathLike[str], **options: Any) -> dict[str, Any]: ...
    def __len__(self) -> int: ...
    def _tree(self, *, flavor: str = ..., first_dim: str = ..., passthrough: str = ...) -> dict[str, Any]: ...

def read(source: Source, *, station: str | None = None, volume: int = 0) -> Volume: ...
def read_all(source: Source, *, station: str | None = None, all_stations: bool = False) -> list[Volume]: ...
def merge(volumes: list[Volume]) -> Volume: ...
def split_scan_cycles(volume: Volume) -> list[Volume]: ...
def sniff(data: bytes) -> str: ...
def pyart_field_name(name: str, mode: str = "config", source_format: str = "unknown") -> str: ...
def writers() -> list[tuple[str, bool]]: ...
def publisher_available() -> bool: ...
def _open_tree(
    source: Source,
    *,
    flavor: str = "xradar",
    first_dim: str = "auto",
    passthrough: str = "flavor",
    station: str | None = None,
    volume: int = 0,
) -> dict[str, Any]: ...
def _dump(
    source: Source,
    *,
    data: bool = False,
    rays: bool = False,
    station: str | None = None,
    all_stations: bool = False,
) -> str: ...
def _write(
    volume: Volume, path: str, format: str, **options: Any
) -> tuple[str, tuple[list[str], list[str]]]: ...
def _to_bytes(volume: Volume, format: str, **options: Any) -> tuple[bytes, tuple[list[str], list[str]]]: ...
def _publish(volume: Volume, root: str, **options: Any) -> dict[str, Any]: ...
def _write_chunks(
    volume: Volume, *, site: str | None = None, **options: Any
) -> tuple[list[tuple[str, str, int, bytes]], tuple[list[str], list[str]]]: ...
def _require_writer(format: str) -> None: ...

# Shared product processing, native rendering, and bundled command line.
def _products() -> str: ...
def _process(volume: Volume, options: str, previous: Volume | None = None) -> tuple[Volume, str]: ...
def _render(volume: Volume, **options: Any) -> Any: ...
def _cli(args: list[str]) -> int: ...

def _section(volume: Volume, options: str) -> dict[str, Any]: ...
def _grid(volumes: list[Volume], options: str) -> dict[str, Any]: ...
