//! Framing, headers, block walking and packet dispatch against the real Level III
//! corpus (`testdata/level3/manifest.toml`) and its golden JSON
//! (`testdata/level3/golden/<id>.json`, generated by `tools/level3_golden.py`).
//!
//! Golden values come from two independent readers: the ICD walker in
//! `level3_golden.py` (framing, raw halfwords, block/page structure, packet
//! codes) and MetPy 1.7.1 `Level3File` (decoded Product Description Block fields
//! and times). Packet contents are checked by the packet family tests; here only
//! packet codes and sizes are compared, so the test holds whether a packet is
//! decoded or still `Packet::Unknown`.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod common;

use common::{Entry, Json};
use recast_radar_io_level3::{
    GraphicAlphanumeric, GraphicLayout, Level3Error, Level3Product, Packet, TabularLayout,
    decode_product, product_info, products,
};

/// Records a mismatch between a decoded value and its golden value.
macro_rules! check_eq {
    ($problems:expr, $what:expr, $decoded:expr, $golden:expr $(,)?) => {{
        let (decoded, golden) = (&$decoded, &$golden);
        if decoded != golden {
            $problems.push(format!(
                "{}: decoded {:?}, golden {:?}",
                $what, decoded, golden
            ));
        }
    }};
}

#[derive(Default)]
struct Counts {
    products: usize,
    not_a_product: usize,
    text_only: usize,
    compressed: usize,
    zlib: usize,
    metpy_header_checks: usize,
}

#[test]
fn corpus_framing_matches_golden() {
    let entries = common::level3_manifest();
    assert!(!entries.is_empty(), "the Level III manifest lists no files");
    let mut counts = Counts::default();
    let mut failures = Vec::new();
    for entry in &entries {
        assert_eq!(
            entry.format, "nexrad-level3",
            "{}: unexpected format",
            entry.id
        );
        let problems = check_file(entry, &mut counts);
        if !problems.is_empty() {
            failures.push(format!("{}:\n    {}", entry.id, problems.join("\n    ")));
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} files differ from golden:\n{}",
        failures.len(),
        entries.len(),
        failures.join("\n")
    );
    // Every framing path in the corpus was exercised.
    assert!(
        counts.not_a_product > 0
            && counts.text_only > 0
            && counts.compressed > 0
            && counts.zlib > 0
    );
    assert!(counts.metpy_header_checks > 0);
    eprintln!(
        "{} files: {} products ({} bzip2, {} zlib-wrapped, {} with header fields cross-checked against MetPy), \
         {} without a product description block, {} text-only",
        entries.len(),
        counts.products,
        counts.compressed,
        counts.zlib,
        counts.metpy_header_checks,
        counts.not_a_product,
        counts.text_only
    );
}

#[test]
fn product_table_is_sorted_and_covers_the_corpus() {
    let table = products();
    assert!(
        table.windows(2).all(|w| w[0].code < w[1].code),
        "product table not strictly sorted"
    );
    for info in table {
        assert!(!info.name.is_empty(), "product {} has no name", info.code);
        assert_eq!(product_info(info.code), Some(info));
    }
    assert_eq!(product_info(0), None);
    assert_eq!(product_info(-1), None);

    for entry in common::level3_manifest() {
        let golden = entry.golden();
        let Some(code) = golden.get("product_code").as_i64() else {
            continue;
        };
        let code = i16::try_from(code).unwrap();
        let info = product_info(code)
            .unwrap_or_else(|| panic!("{}: product {code} not in the table", entry.id));
        if let Some(mnemonic) = entry.tag("mnemonic") {
            assert_eq!(
                info.mnemonic, mnemonic,
                "{}: mnemonic of product {code}",
                entry.id
            );
        }
    }
}

/// Real files cut short at header, block and midpoint boundaries decode to
/// `Ok` or an error, never a panic, and a cut inside the Product Description
/// Block is always an error.
#[test]
fn truncated_corpus_files_do_not_panic() {
    let mut failures = Vec::new();
    for entry in common::level3_manifest() {
        let bytes = entry.bytes();
        let golden = entry.golden();
        let framing = golden.get("framing");
        let trailer = if framing.get("trailer").is_null() {
            0
        } else {
            4
        };
        // Bytes of NOAAPort/WMO/AWIPS heading in front of an unwrapped message.
        let framed_prefix =
            bytes.len() as i64 - trailer - framing.get("message_bytes").int("message_bytes");
        let mut cuts = vec![
            0,
            1,
            17,
            18,
            19,
            60,
            119,
            120,
            121,
            200,
            bytes.len() / 2,
            bytes.len() - 1,
        ];
        cuts.retain(|&cut| cut < bytes.len());
        for cut in cuts {
            let prefix = &bytes[..cut];
            match std::panic::catch_unwind(|| decode_product(prefix)) {
                Err(_) => failures.push(format!("{} cut at {cut}: panicked", entry.id)),
                Ok(Ok(_))
                    if framing.get("zlib_frames").int("zlib_frames") == 0
                        && (cut as i64) < framed_prefix + 120 =>
                {
                    failures.push(format!(
                        "{} cut at {cut}: decoded a product without a full description block",
                        entry.id
                    ));
                }
                Ok(_) => {}
            }
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

fn describe(result: &Result<Level3Product, Level3Error>) -> String {
    match result {
        Ok(product) => format!("a product with code {}", product.description.product_code),
        Err(e) => format!("error: {e}"),
    }
}

fn check_file(entry: &Entry, counts: &mut Counts) -> Vec<String> {
    let mut problems = Vec::new();
    let golden = entry.golden();
    let framing = golden.get("framing");
    let result = decode_product(&entry.bytes());

    if framing.get("text_only").as_bool() == Some(true) {
        match &result {
            Err(Level3Error::TextOnly { heading }) => {
                counts.text_only += 1;
                check_eq!(
                    problems,
                    "text-only heading",
                    Some(heading.as_str()),
                    framing.get("wmo_heading").as_str()
                );
            }
            other => problems.push(format!(
                "expected a text-only message, got {}",
                describe(other)
            )),
        }
        return problems;
    }
    if golden.get("product_code").is_null() {
        let code = golden
            .get("message_header")
            .get("code")
            .int("message_header.code");
        match &result {
            Err(Level3Error::NotAProduct { code: decoded }) => {
                counts.not_a_product += 1;
                check_eq!(problems, "message code", i64::from(*decoded), code);
            }
            other => problems.push(format!(
                "expected a message without product description, got {}",
                describe(other)
            )),
        }
        return problems;
    }
    let product = match result {
        Ok(product) => product,
        Err(e) => {
            problems.push(format!("decode failed: {e}"));
            return problems;
        }
    };
    counts.products += 1;
    counts.compressed += usize::from(product.description.compressed);
    counts.zlib += usize::from(
        product
            .text_header
            .as_ref()
            .is_some_and(|t| t.zlib_frames > 0),
    );

    check_text_header(&product, framing, &mut problems);
    check_message_header(&product, golden.get("message_header"), &mut problems);
    check_description(&product, &golden, counts, &mut problems);
    check_blocks(&product, &golden, &mut problems);
    problems
}

fn check_text_header(product: &Level3Product, framing: &Json, problems: &mut Vec<String>) {
    let golden_heading = framing
        .get("wmo_heading")
        .as_str()
        .or(framing.get("inner_wmo_heading").as_str());
    let Some(header) = &product.text_header else {
        if golden_heading.is_some() {
            problems.push(format!(
                "no text header decoded, golden heading {golden_heading:?}"
            ));
        }
        return;
    };
    check_eq!(
        problems,
        "WMO heading",
        Some(header.wmo_heading.as_str()),
        golden_heading
    );
    let awips = framing
        .get("awips_id")
        .as_str()
        .or(framing.get("inner_awips_id").as_str());
    check_eq!(problems, "AWIPS id", header.awips_id.as_deref(), awips);
    check_eq!(
        problems,
        "NOAAPort sequence",
        header.noaaport_sequence.as_deref(),
        framing.get("noaaport_sequence").as_str()
    );
    check_eq!(
        problems,
        "zlib frames",
        i64::from(header.zlib_frames),
        framing.get("zlib_frames").int("zlib_frames")
    );
    let mut rebuilt = format!(
        "{} {} {}",
        header.data_designator, header.originator, header.day_time
    );
    if let Some(indicator) = &header.indicator {
        rebuilt = format!("{rebuilt} {indicator}");
    }
    check_eq!(problems, "WMO heading parts", rebuilt, header.wmo_heading);
}

fn check_message_header(product: &Level3Product, golden: &Json, problems: &mut Vec<String>) {
    let h = &product.message_header;
    let fields = [
        ("code", i64::from(h.code)),
        ("date", i64::from(h.date)),
        ("time", i64::from(h.time)),
        ("length", i64::from(h.length)),
        ("source_id", i64::from(h.source_id)),
        ("destination_id", i64::from(h.destination_id)),
        ("num_blocks", i64::from(h.num_blocks)),
    ];
    for (name, decoded) in fields {
        check_eq!(
            problems,
            format!("message_header.{name}"),
            decoded,
            golden.get(name).int(name)
        );
    }
}

/// Seconds since 1970 for MetPy's `YYYY-MM-DDTHH:MM:SS.ffffffZ` timestamps.
fn iso_to_unix(text: &str) -> i64 {
    let num = |range: std::ops::Range<usize>| text[range].parse::<i64>().unwrap();
    let (y, m, d) = (num(0..4), num(5..7), num(8..10));
    // Days from civil (Howard Hinnant's algorithm).
    let y = if m <= 2 { y - 1 } else { y };
    let era = y.div_euclid(400);
    let yoe = y - era * 400;
    let doy = (153 * (if m > 2 { m - 3 } else { m + 9 }) + 2) / 5 + d - 1;
    let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    let days = era * 146_097 + doe - 719_468;
    days * 86_400 + num(11..13) * 3600 + num(14..16) * 60 + num(17..19)
}

fn check_description(
    product: &Level3Product,
    golden: &Json,
    counts: &mut Counts,
    problems: &mut Vec<String>,
) {
    let d = &product.description;
    let halfwords: Vec<i64> = d.halfwords.iter().map(|&h| i64::from(h)).collect();
    let golden_halfwords: Vec<i64> = golden
        .get("halfwords")
        .items()
        .iter()
        .map(|h| h.int("halfword"))
        .collect();
    check_eq!(problems, "halfwords 1-60", halfwords, golden_halfwords);
    check_eq!(
        problems,
        "product code",
        i64::from(d.product_code),
        golden.get("product_code").int("product_code")
    );
    check_eq!(
        problems,
        "halfword(16)",
        d.halfword(16).map(i64::from),
        Some(i64::from(d.product_code as u16))
    );
    check_eq!(
        problems,
        "bzip2 compressed",
        Some(d.compressed),
        golden.get("compression").get("bzip2").as_bool()
    );

    // Decoded fields against MetPy's Product Description Block, where MetPy read the file.
    let detail = golden.get("metpy_detail");
    let pd = detail.get("prod_desc");
    if pd.is_null() {
        return;
    }
    counts.metpy_header_checks += 1;
    let close = |a: f64, b: f64| (a - b).abs() < 1e-9;
    let lat = pd.get("lat").int("lat") as f64 * 0.001;
    let lon = pd.get("lon").int("lon") as f64 * 0.001;
    if !close(d.latitude_deg, lat) || !close(d.longitude_deg, lon) {
        problems.push(format!(
            "lat/lon: decoded {} {}, MetPy {lat} {lon}",
            d.latitude_deg, d.longitude_deg
        ));
    }
    let fields = [
        ("height", i64::from(d.height_ft)),
        ("prod_code", i64::from(d.product_code)),
        ("op_mode", i64::from(d.operational_mode)),
        ("vcp", i64::from(d.vcp)),
        ("seq_num", i64::from(d.sequence_number)),
        ("vol_num", i64::from(d.volume_scan_number)),
        ("el_num", i64::from(d.elevation_number)),
        ("version", i64::from(d.version)),
        ("spot_blank", i64::from(d.spot_blank)),
        ("sym_off", i64::from(d.symbology_offset)),
        ("graph_off", i64::from(d.graphic_offset)),
        ("tab_off", i64::from(d.tabular_offset)),
    ];
    for (name, decoded) in fields {
        check_eq!(
            problems,
            format!("prod_desc.{name} (MetPy)"),
            decoded,
            pd.get(name).int(name)
        );
    }
    let metadata = detail.get("metadata");
    for (name, decoded) in [
        ("vol_time", d.volume_scan_time),
        ("prod_time", d.generation_time),
    ] {
        if let Some(text) = metadata.get(name).as_str() {
            check_eq!(
                problems,
                format!("{name} (MetPy)"),
                decoded.timestamp(),
                iso_to_unix(text)
            );
        }
    }
}

fn codes(packets: &[Packet]) -> Vec<i64> {
    packets.iter().map(|p| i64::from(p.code())).collect()
}

/// When every packet is still `Unknown`, their byte lengths must add up to the
/// golden layer or page length (checks packet sizing).
fn check_unknown_sizes(
    what: &str,
    packets: &[Packet],
    golden_length: &Json,
    problems: &mut Vec<String>,
) {
    let mut total = 0;
    for packet in packets {
        match packet {
            Packet::Unknown { bytes, code } => {
                total += bytes.len();
                if bytes.get(..2) != Some(&code.to_be_bytes()[..]) {
                    problems.push(format!(
                        "{what}: unknown packet {code} bytes do not start with its code"
                    ));
                }
            }
            _ => return,
        }
    }
    if let Some(length) = golden_length.as_i64() {
        check_eq!(
            problems,
            format!("{what} packet bytes"),
            total as i64,
            length
        );
    }
}

fn golden_codes(json: &Json) -> Vec<i64> {
    json.items().iter().map(|c| c.int("packet code")).collect()
}

fn check_blocks(product: &Level3Product, golden: &Json, problems: &mut Vec<String>) {
    let blocks = golden.get("blocks");
    let mut all_codes: Vec<i64> = Vec::new();

    // Symbology block: top-level packet codes per layer.
    let golden_sym = blocks.get("symbology");
    match (&product.symbology, golden_sym.is_null()) {
        (None, true) => {}
        (Some(sym), false) => {
            let golden_layers = golden_sym.get("layers").items();
            check_eq!(
                problems,
                "symbology layer count",
                sym.layers.len(),
                golden_layers.len()
            );
            for (i, (layer, golden_layer)) in sym.layers.iter().zip(golden_layers).enumerate() {
                check_eq!(
                    problems,
                    format!("symbology layer {i} packet codes"),
                    codes(layer),
                    golden_codes(golden_layer.get("packets"))
                );
                check_unknown_sizes(
                    &format!("symbology layer {i}"),
                    layer,
                    golden_layer.get("length"),
                    problems,
                );
                all_codes.extend(codes(layer));
            }
            for nested in golden_sym.get("nested").items() {
                all_codes.extend(golden_codes(nested.get("packets")));
            }
        }
        (decoded, _) => problems.push(format!(
            "symbology block presence: decoded {}, golden {}",
            decoded.is_some(),
            !golden_sym.is_null()
        )),
    }

    // Graphic alphanumeric block, or product 62 cell trend data.
    let golden_graphic = blocks.get("graphic");
    let golden_trend = blocks.get("cell_trend");
    match &product.graphic {
        None => {
            if !golden_graphic.is_null() || !golden_trend.is_null() {
                problems.push("graphic block or cell trend data missing".into());
            }
        }
        Some(GraphicAlphanumeric {
            layout: GraphicLayout::Pages,
            pages,
            ..
        }) if !golden_graphic.is_null() => {
            let golden_pages = golden_graphic.get("pages").items();
            check_eq!(
                problems,
                "graphic page count",
                pages.len(),
                golden_pages.len()
            );
            for (page, golden_page) in pages.iter().zip(golden_pages) {
                let what = format!("graphic page {}", page.number);
                check_eq!(
                    problems,
                    format!("{what} number"),
                    i64::from(page.number),
                    golden_page.get("page").int("page")
                );
                check_eq!(
                    problems,
                    format!("{what} packet codes"),
                    codes(&page.packets),
                    golden_codes(golden_page.get("packets"))
                );
                check_unknown_sizes(&what, &page.packets, golden_page.get("length"), problems);
                all_codes.extend(codes(&page.packets));
            }
        }
        Some(GraphicAlphanumeric {
            layout: GraphicLayout::CellTrend,
            pages,
            ..
        }) if !golden_trend.is_null() => {
            let decoded: Vec<Vec<i64>> = pages.iter().map(|p| codes(&p.packets)).collect();
            check_eq!(
                problems,
                "cell trend packet codes",
                decoded,
                vec![golden_codes(golden_trend.get("packets"))]
            );
            all_codes.extend(decoded.into_iter().flatten());
        }
        Some(graphic) => problems.push(format!(
            "graphic layout {:?} does not match golden (graphic {}, cell_trend {})",
            graphic.layout,
            !golden_graphic.is_null(),
            !golden_trend.is_null()
        )),
    }

    // Tabular data.
    let golden_tab = blocks.get("tabular");
    let golden_standalone = blocks.get("standalone_tabular");
    let golden_rcm = blocks.get("rcm");
    match &product.tabular {
        None => {
            if !(golden_tab.is_null() && golden_standalone.is_null() && golden_rcm.is_null()) {
                problems.push("tabular data missing".into());
            }
        }
        Some(tab) => match tab.layout {
            TabularLayout::Block if !golden_tab.is_null() => {
                check_eq!(
                    problems,
                    "tabular block message code",
                    tab.message_header.map(|h| i64::from(h.code)),
                    golden_tab.get("message_code").as_i64()
                );
                // The walker reads the product code without checking the second
                // block's divider. Observed: product 171 (KTLX 2013) has a zeroed
                // second Product Description Block (no -1 divider), which decodes
                // to `None` and which the walker reports as product code 0.
                check_eq!(
                    problems,
                    "tabular block product code",
                    Some(tab.description.as_ref().map_or(0, |d| i64::from(d.product_code))),
                    golden_tab.get("product_code").as_i64()
                );
                check_page_count("tabular block", &tab.data, golden_tab, problems);
            }
            TabularLayout::StandAlone if !golden_standalone.is_null() => {
                check_page_count("stand-alone tabular", &tab.data, golden_standalone, problems);
            }
            TabularLayout::RadarCodedMessage if !golden_rcm.is_null() => {
                check_eq!(problems, "radar coded message bytes", tab.data.len() as i64, golden_rcm.get("text_bytes").int("text_bytes"));
                check_eq!(problems, "radar coded message start", tab.data.get(..10), Some(&b"1234 ROBUU"[..]));
            }
            layout => problems.push(format!(
                "tabular layout {layout:?} does not match golden (tabular {}, stand-alone {}, rcm {})",
                !golden_tab.is_null(),
                !golden_standalone.is_null(),
                !golden_rcm.is_null()
            )),
        },
    }

    // Every packet code the golden walker saw was found (nested SCIT contents from golden).
    all_codes.sort_unstable();
    all_codes.dedup();
    check_eq!(
        problems,
        "packet codes present",
        all_codes,
        golden_codes(golden.get("packet_codes"))
    );
}

/// A page block starts with divider -1 and the page count (ICD Figure 3-16).
fn check_page_count(what: &str, data: &[u8], golden: &Json, problems: &mut Vec<String>) {
    match data {
        [0xFF, 0xFF, hi, lo, ..] => {
            check_eq!(
                problems,
                format!("{what} page count"),
                i64::from(i16::from_be_bytes([*hi, *lo])),
                golden.get("num_pages").int("num_pages")
            );
        }
        _ => problems.push(format!(
            "{what}: data does not start with a page block divider"
        )),
    }
}
