//! Raster packet family (Task L3.3): Raster Data Packet (0xBA07, 0xBA0F, ICD
//! 2620001 Figure 3-11), Digital Precipitation Data Array (17, Figure 3-11a),
//! Precipitation Rate Data Array (18, Figure 3-11b) and Digital Raster Data
//! Array (33, Figure 3-11d), against the real Level III corpus
//! (`testdata/level3/manifest.toml`) and its golden JSON
//! (`testdata/level3/golden/<id>.json`, generated by `tools/level3_golden.py`).
//!
//! Golden raster values come from MetPy 1.7.1 `Level3File`: the level grid of
//! each packet (`raw_sha256` of the row-major `u8` levels, `histogram`, `rows` x
//! `cols`) and, for products MetPy maps, a summary of `map_data` physical values.
//! Packet header fields come from the ICD walker in the golden tool (a second
//! reading by the decoder's author).
//!
//! Physical values come from the public API: [`DataLevels::for_packet`] and
//! [`RasterGrid::values`] (`f32`, NaN without a value). Their finite/masked
//! counts and min/max/mean equal MetPy's for every raster product MetPy maps
//! ([`METPY_MAPPED_PRODUCTS`]: threshold-coded products and product 81's
//! packet 17). MetPy maps no packet 18 levels; `for_packet` gives them the
//! 8-level rate code of ICD 2620003AE section 30.2.1, which the test checks
//! level by level.
//!
//! Corpus coverage: 0xBA07 in 29 files, 17 in 4, 18 in 4. No real sample of
//! 0xBA0F or 33 exists (reference section 7), so those codes are decoded by the
//! same code paths but have no corpus check. MetPy cannot read one raster file,
//! `l3-fws-sup-19950517-2304` (product 82); it is checked against an ICD
//! reading of its bytes in [`product_82_precipitation_rate_array_matches_icd_reading`].

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod common;

use std::collections::{BTreeMap, BTreeSet};

use common::{Entry, Json, PhysicalSummary};
use recast_radar_io_level3::levels::{DataLevels, Level};
use recast_radar_io_level3::packets::raster::{RasterGrid, RasterHeader};
use recast_radar_io_level3::{Level3Error, Level3Product, Packet, decode_product};

/// Packet codes of the raster family.
const FAMILY_CODES: [u16; 5] = [0xBA07, 0xBA0F, 17, 18, 33];

/// Products whose raster packets MetPy maps to physical values, all compared:
/// 16-level threshold products (0xBA07) and product 81 (packet 17).
const METPY_MAPPED_PRODUCTS: [i16; 17] = [
    35, 36, 37, 38, 41, 50, 51, 57, 63, 64, 65, 66, 67, 78, 80, 81, 90,
];

/// Files MetPy cannot read that contain raster packets; each is checked by its
/// own ICD-based test below.
const ICD_CHECKED: [&str; 1] = ["l3-fws-sup-19950517-2304"];

/// Records a mismatch between a decoded value and its golden value.
macro_rules! check_eq {
    ($problems:expr, $what:expr, $decoded:expr, $golden:expr $(,)?) => {{
        let (decoded, golden) = (&$decoded, &$golden);
        if decoded != golden {
            $problems.push(format!(
                "{}: decoded {:?}, golden {:?}",
                $what, decoded, golden
            ));
        }
    }};
}

#[derive(Default, Debug)]
struct Counts {
    /// Files per family packet code.
    files: BTreeMap<u16, usize>,
    /// Decoded packets per family packet code.
    packets: BTreeMap<u16, usize>,
    /// Packets whose level grid was compared with MetPy's.
    grids_checked: usize,
    /// Packets whose physical summary was compared with MetPy's.
    physical_checked: usize,
    /// Product codes of those packets.
    physical_products: BTreeSet<i16>,
    /// Packets MetPy maps no physical values for, checked against the ICD
    /// 2620003AE 8-level rate code instead (packet 18).
    unmapped_checked: usize,
}

#[test]
fn raster_packets_match_golden() {
    let mut counts = Counts::default();
    let mut failures = Vec::new();
    for entry in common::level3_manifest() {
        let golden = entry.golden();
        let expected = common::golden_top_level_counts(&golden, &FAMILY_CODES);
        if expected.is_empty() {
            continue;
        }
        for code in expected.keys() {
            *counts.files.entry(*code).or_default() += 1;
        }
        let problems = check_file(&entry, &golden, &expected, &mut counts);
        if !problems.is_empty() {
            failures.push(format!("{}:\n    {}", entry.id, problems.join("\n    ")));
        }
    }
    assert!(
        failures.is_empty(),
        "{} files differ from golden:\n{}",
        failures.len(),
        failures.join("\n")
    );
    eprintln!("{counts:?}");
    // Every raster packet code with a real sample was decoded and compared.
    assert_eq!(counts.files.get(&0xBA07), Some(&37));
    assert_eq!(counts.files.get(&17), Some(&4));
    assert_eq!(counts.files.get(&18), Some(&4));
    // Packet 18: 40 layers of the three DPA files MetPy reads, plus product 82;
    // 0xBA07: one per raster product, eight in each Weak Echo Region (53).
    let packets: Vec<(u16, usize)> = counts.packets.iter().map(|(c, n)| (*c, *n)).collect();
    assert_eq!(packets, [(17, 4), (18, 41), (0xBA07, 51)]);
    // Every packet in a file MetPy reads: 51 + 4 + 40 level grids, physical
    // values for the 0xBA07 and 17 packets (MetPy maps no packet 18, nor the
    // rasters of products 53 and 87, which are checked against the ICD).
    assert_eq!(counts.grids_checked, 95);
    assert_eq!(counts.physical_checked, 38);
    assert_eq!(counts.unmapped_checked, 57);
    assert_eq!(
        counts.physical_products,
        BTreeSet::from(METPY_MAPPED_PRODUCTS)
    );
}

/// Product 82 (Supplemental Precipitation Data) from KFWS 1995: MetPy 1.7.1
/// raises `UnicodeDecodeError` on it (it expects a stand-alone tabular product),
/// so the expected values are an ICD reading of the file's own bytes.
///
/// The symbology block is at halfword 60 (byte 120 of the message); layer 0 (90
/// bytes) holds one packet 18 whose header is `00 12` (code 18), `00 00 00 00`
/// (two spares), `00 0d` (13 LFM boxes per row), `00 0d` (13 rows), followed by
/// 13 rows of `INT*2` byte count and 4-bit run / 4-bit level bytes (Figure
/// 3-11b). For example row 0 is `00 04 47 40 57 00`: 4 x level 7, 4 x level 0,
/// 5 x level 7, and a zero pad byte (run 0). The grid below expands every row
/// that way; each expands to exactly 13 boxes. Layer 1 holds packet 1 (text family).
#[test]
fn product_82_precipitation_rate_array_matches_icd_reading() {
    const EXPECTED: [[u8; 13]; 13] = [
        [7, 7, 7, 7, 0, 0, 0, 0, 7, 7, 7, 7, 7],
        [7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 7],
        [7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7],
        [7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7],
        [0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 7],
        [7, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 7],
        [7, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 7, 7],
        [7, 7, 0, 0, 3, 0, 0, 0, 0, 0, 0, 7, 7],
        [7, 7, 7, 7, 0, 0, 0, 0, 0, 7, 7, 7, 7],
    ];
    let entry = common::entry("l3-fws-sup-19950517-2304");
    assert_eq!(entry.golden().get("metpy").as_str(), Some("unsupported"));
    let product = decode_product(&entry.bytes()).unwrap();
    assert_eq!(product.description.product_code, 82);
    assert_eq!(product.description.symbology_offset, 60);
    let layers = &product.symbology.as_ref().unwrap().layers;
    assert_eq!(layers.len(), 2);
    assert_eq!(layers[0].len(), 1);
    let Packet::Raster(packet) = &layers[0][0] else {
        panic!(
            "layer 0: expected a decoded packet 18, got {:?}",
            layers[0][0]
        );
    };
    assert_eq!(packet.code, 18);
    assert_eq!(packet.code(), 18);
    assert_eq!(
        packet.header,
        RasterHeader::PrecipitationRate { spares: [0, 0] }
    );
    assert_eq!(packet.grid.rows(), 13);
    assert_eq!(packet.grid.columns(), 13);
    let rows: Vec<&[u8]> = packet.grid.iter_rows().collect();
    let expected: Vec<&[u8]> = EXPECTED.iter().map(|row| row.as_slice()).collect();
    assert_eq!(rows, expected);
    check_grid_accessors(&packet.grid).unwrap();
}

/// Real raster packets with one header field or run byte changed are rejected
/// with [`Level3Error::InvalidPacket`], and no single-byte change to a real
/// packet's header or first rows panics.
#[test]
fn corrupted_raster_packets_are_rejected_without_panic() {
    // KTLX 2013 composite reflectivity: layer 0 is one 0xBA07 packet.
    let ncr = RealPacket::locate("l3-tlx-ncr-20130520-2016", 0, 0xBA07);
    // Packing descriptor (packet bytes 20-21) other than 2.
    assert_invalid(&ncr.with(20, &[0x00, 0x03]), 0xBA07);
    // First row's first run shortened or lengthened by one: rows differ in width.
    let first_run = ncr.packet()[24];
    let changed = if first_run >> 4 == 15 {
        first_run - 0x10
    } else {
        first_run + 0x10
    };
    assert_invalid(&ncr.with(24, &[changed]), 0xBA07);

    // KTLX 2013 digital precipitation array: layer 0 is packet 17, layer 1 packet 18.
    let dpa17 = RealPacket::locate("l3-tlx-dpa-20130520-2016", 0, 17);
    let dpa18 = RealPacket::locate("l3-tlx-dpa-20130520-2016", 1, 18);
    // LFM boxes per row (packet bytes 6-7) no longer matching the row contents.
    for boxes in [0u16, 130, 132, 0xFFFF] {
        assert_invalid(&dpa17.with(6, &boxes.to_be_bytes()), 17);
        assert_invalid(&dpa18.with(6, &boxes.to_be_bytes()), 18);
    }

    let mut panics = Vec::new();
    for real in [&ncr, &dpa17, &dpa18] {
        let limit = real.len.min(160);
        for i in 0..limit {
            for value in [0x00, 0x11, 0xFF] {
                let mutated = real.with(i, &[value]);
                if std::panic::catch_unwind(|| decode_product(&mutated)).is_err() {
                    panics.push(format!("{} packet byte {i} = {value:#04x}", real.id));
                }
            }
        }
    }
    assert!(panics.is_empty(), "panicked:\n{}", panics.join("\n"));
}

/// Every header field is read from its own ICD offset. The corpus cannot show
/// this on its own: in every real raster packet I start equals J start and X
/// scale equals Y scale. Distinct values written into real headers must come
/// back in exactly the matching fields, with the grid unchanged.
#[test]
fn raster_header_fields_come_from_their_icd_offsets() {
    let ncr = RealPacket::locate("l3-tlx-ncr-20130520-2016", 0, 0xBA07);
    let Packet::Raster(original) = ncr.decoded(&ncr.bytes) else {
        unreachable!()
    };
    // Figure 3-11 halfwords 2-9: op flags, I start, J start, X scale integer and
    // fraction, Y scale integer and fraction.
    let values: [u16; 8] = [
        0x8001, 0x00C2, 0xFFFD, 0x0007, 0x0003, 0x0011, 0x0005, 0x0013,
    ];
    let patch: Vec<u8> = values.iter().flat_map(|v| v.to_be_bytes()).collect();
    let Packet::Raster(patched) = ncr.decoded(&ncr.with(2, &patch)) else {
        panic!("patched 0xBA07 packet not decoded");
    };
    assert_eq!(
        patched.header,
        RasterHeader::RasterData {
            op_flags: [0x8001, 0x00C2],
            i_start: -3,
            j_start: 7,
            x_scale: 3,
            x_scale_fraction: 17,
            y_scale: 5,
            y_scale_fraction: 19,
            packing: 2,
        }
    );
    assert_eq!(patched.grid, original.grid);

    // Figure 3-11a/b halfwords 2-3: the two spares.
    for (layer, code) in [(0, 17), (1, 18)] {
        let real = RealPacket::locate("l3-tlx-dpa-20130520-2016", layer, code);
        let original = real.decoded(&real.bytes);
        let patched = real.decoded(&real.with(2, &[0x12, 0x34, 0x56, 0x78]));
        match (original, patched) {
            (Packet::DigitalPrecip(original), Packet::DigitalPrecip(patched)) => {
                assert_eq!(original.spares, [0, 0]);
                assert_eq!(patched.spares, [0x1234, 0x5678]);
                assert_eq!(patched.grid, original.grid);
            }
            (Packet::Raster(original), Packet::Raster(patched)) => {
                assert_eq!(
                    original.header,
                    RasterHeader::PrecipitationRate { spares: [0, 0] }
                );
                assert_eq!(
                    patched.header,
                    RasterHeader::PrecipitationRate {
                        spares: [0x1234, 0x5678]
                    }
                );
                assert_eq!(patched.grid, original.grid);
            }
            other => panic!("packet {code}: unexpected variants {other:?}"),
        }
    }
}

/// A packet inside a real, uncompressed, unwrapped corpus file.
struct RealPacket {
    id: &'static str,
    bytes: Vec<u8>,
    /// Symbology layer holding the packet (as its only packet).
    layer: usize,
    /// File offset of the packet code.
    offset: usize,
    /// Packet length in bytes.
    len: usize,
}

impl RealPacket {
    /// The first packet of symbology layer `layer`, which must have `code`.
    fn locate(id: &'static str, layer: usize, code: u16) -> Self {
        let entry = common::entry(id);
        let golden = entry.golden();
        let bytes = entry.bytes();
        let message_start = common::uncompressed_message_start(&golden, bytes.len());
        let symbology = golden.get("blocks").get("symbology");
        let halfwords = golden.get("halfwords").items();
        let offset_hw = (halfwords[54].int("hw55") << 16) | halfwords[55].int("hw56");
        // Block header (divider, ID, length, layer count) is 10 bytes; each layer
        // header (divider, length) is 6 bytes.
        let mut offset = message_start + 2 * usize::try_from(offset_hw).unwrap() + 10;
        let layers = symbology.get("layers").items();
        for skipped in &layers[..layer] {
            offset += 6 + usize::try_from(skipped.get("length").int("layer length")).unwrap();
        }
        offset += 6;
        assert_eq!(
            u16::from_be_bytes([bytes[offset], bytes[offset + 1]]),
            code,
            "{id}: packet code at file byte {offset}"
        );
        assert_eq!(layers[layer].get("packets").items().len(), 1);
        let len = usize::try_from(layers[layer].get("length").int("layer length")).unwrap();
        let located = Self {
            id,
            bytes,
            layer,
            offset,
            len,
        };
        // The unmodified file decodes, with this packet decoded.
        let packet = located.decoded(&located.bytes);
        assert!(
            matches!(packet, Packet::Raster(_) | Packet::DigitalPrecip(_)),
            "{id}: layer {layer} packet not decoded: {packet:?}"
        );
        located
    }

    /// The packet decoded from `file` (this file, possibly patched).
    fn decoded(&self, file: &[u8]) -> Packet {
        let product = decode_product(file).unwrap_or_else(|e| panic!("{}: {e}", self.id));
        product
            .symbology
            .unwrap()
            .layers
            .swap_remove(self.layer)
            .swap_remove(0)
    }

    fn packet(&self) -> &[u8] {
        &self.bytes[self.offset..self.offset + self.len]
    }

    /// The file with `patch` written at packet byte `at`.
    fn with(&self, at: usize, patch: &[u8]) -> Vec<u8> {
        let mut bytes = self.bytes.clone();
        bytes[self.offset + at..self.offset + at + patch.len()].copy_from_slice(patch);
        bytes
    }
}

fn assert_invalid(bytes: &[u8], code: u16) {
    match decode_product(bytes) {
        Err(Level3Error::InvalidPacket { code: found, .. }) if found == code => {}
        other => panic!(
            "expected InvalidPacket for packet {code}, got {}",
            match other {
                Ok(_) => "a decoded product".to_string(),
                Err(e) => format!("error: {e}"),
            }
        ),
    }
}

fn check_file(
    entry: &Entry,
    golden: &Json,
    expected: &BTreeMap<u16, usize>,
    counts: &mut Counts,
) -> Vec<String> {
    let mut problems = Vec::new();
    let bytes = entry.bytes();
    let product = match decode_product(&bytes) {
        Ok(product) => product,
        Err(e) => return vec![format!("decode failed: {e}")],
    };

    // Every family packet anywhere in the product is decoded.
    let mut decoded = BTreeMap::new();
    for (place, packet) in all_packets(&product) {
        let code = packet.code();
        if !FAMILY_CODES.contains(&code) {
            continue;
        }
        *decoded.entry(code).or_default() += 1;
        match packet {
            Packet::Raster(p) if code != 17 => {
                if let Err(e) = check_grid_accessors(&p.grid) {
                    problems.push(format!("{place}: {e}"));
                }
            }
            Packet::DigitalPrecip(p) if code == 17 => {
                if let Err(e) = check_grid_accessors(&p.grid) {
                    problems.push(format!("{place}: {e}"));
                }
            }
            other => problems.push(format!(
                "{place}: packet {code} not decoded: {}",
                short(other)
            )),
        }
    }
    check_eq!(problems, "family packet counts", decoded, *expected);
    for (code, n) in &decoded {
        *counts.packets.entry(*code).or_default() += n;
    }

    let data = golden.get("data");
    if data.is_null() {
        if !ICD_CHECKED.contains(&entry.id.as_str()) {
            problems.push(format!(
                "MetPy status {:?} and no ICD-based test for this file",
                golden.get("metpy").as_str()
            ));
        }
        return problems;
    }
    let symbology_family = product.symbology.as_ref().map_or(0, |s| {
        s.layers
            .iter()
            .flatten()
            .filter(|p| FAMILY_CODES.contains(&p.code()))
            .count()
    });
    let mut compared = 0;
    for item in data.items() {
        let code = u16::try_from(item.get("packet").int("data.packet")).unwrap();
        if !FAMILY_CODES.contains(&code) {
            continue;
        }
        compared += 1;
        let layer = usize::try_from(item.get("layer").int("data.layer")).unwrap();
        let index = usize::try_from(item.get("index").int("data.index")).unwrap();
        let place = format!("layer {layer} packet {index} (code {code})");
        if let Some(error) = item.get("error").as_str() {
            problems.push(format!("{place}: golden has no grid: {error}"));
            continue;
        }
        let Some(packet) = product
            .symbology
            .as_ref()
            .and_then(|s| s.layers.get(layer))
            .and_then(|l| l.get(index))
        else {
            problems.push(format!("{place}: no such decoded packet"));
            continue;
        };
        let before = problems.len();
        check_packet(&product, packet, code, item, &place, counts, &mut problems);
        if problems.len() == before {
            counts.grids_checked += 1;
        }
    }
    check_eq!(
        problems,
        "symbology family packets compared with MetPy",
        compared,
        symbology_family
    );
    problems
}

/// Every packet in the symbology layers and graphic pages, with its place.
fn all_packets(product: &Level3Product) -> Vec<(String, &Packet)> {
    let mut out = Vec::new();
    if let Some(symbology) = &product.symbology {
        for (l, layer) in symbology.layers.iter().enumerate() {
            for (i, packet) in layer.iter().enumerate() {
                out.push((format!("symbology layer {l} packet {i}"), packet));
            }
        }
    }
    if let Some(graphic) = &product.graphic {
        for page in &graphic.pages {
            for (i, packet) in page.packets.iter().enumerate() {
                out.push((format!("graphic page {} packet {i}", page.number), packet));
            }
        }
    }
    out
}

fn short(packet: &Packet) -> String {
    match packet {
        Packet::Unknown { code, bytes } => {
            format!("Unknown {{ code: {code}, {} bytes }}", bytes.len())
        }
        other => format!("variant for code {}", other.code()),
    }
}

fn check_packet(
    product: &Level3Product,
    packet: &Packet,
    code: u16,
    item: &Json,
    place: &str,
    counts: &mut Counts,
    problems: &mut Vec<String>,
) {
    let header = item.get("header");
    let grid = match packet {
        Packet::Raster(p) => {
            check_eq!(problems, format!("{place}: code"), p.code, code);
            match (code, p.header) {
                (
                    0xBA07 | 0xBA0F,
                    RasterHeader::RasterData {
                        op_flags,
                        i_start,
                        j_start,
                        x_scale,
                        x_scale_fraction,
                        y_scale,
                        y_scale_fraction,
                        packing,
                    },
                ) => {
                    let flags: Vec<i64> = header
                        .get("op_flags")
                        .items()
                        .iter()
                        .map(|f| f.int("op_flags"))
                        .collect();
                    check_eq!(
                        problems,
                        format!("{place}: op_flags"),
                        op_flags.map(i64::from).to_vec(),
                        flags
                    );
                    for (name, value) in [
                        ("i_start", i64::from(i_start)),
                        ("j_start", i64::from(j_start)),
                        ("x_scale_int", i64::from(x_scale)),
                        ("x_scale_frac", i64::from(x_scale_fraction)),
                        ("y_scale_int", i64::from(y_scale)),
                        ("y_scale_frac", i64::from(y_scale_fraction)),
                        ("packing", i64::from(packing)),
                        ("num_rows", p.grid.rows() as i64),
                    ] {
                        check_eq!(
                            problems,
                            format!("{place}: header.{name}"),
                            value,
                            header.get(name).int(name)
                        );
                    }
                }
                (18, RasterHeader::PrecipitationRate { .. }) => {
                    check_eq!(
                        problems,
                        format!("{place}: header.num_boxes"),
                        p.grid.columns() as i64,
                        header.get("num_boxes").int("num_boxes")
                    );
                    check_eq!(
                        problems,
                        format!("{place}: header.num_rows"),
                        p.grid.rows() as i64,
                        header.get("num_rows").int("num_rows")
                    );
                }
                (33, RasterHeader::DigitalRaster { .. }) => {
                    check_eq!(
                        problems,
                        format!("{place}: header.num_cells"),
                        p.grid.columns() as i64,
                        header.get("num_cells").int("num_cells")
                    );
                    check_eq!(
                        problems,
                        format!("{place}: header.num_rows"),
                        p.grid.rows() as i64,
                        header.get("num_rows").int("num_rows")
                    );
                }
                (_, other) => {
                    problems.push(format!(
                        "{place}: header {other:?} does not match code {code}"
                    ));
                    return;
                }
            }
            &p.grid
        }
        Packet::DigitalPrecip(p) if code == 17 => {
            check_eq!(problems, format!("{place}: code"), p.code, code);
            check_eq!(
                problems,
                format!("{place}: header.num_boxes"),
                p.grid.columns() as i64,
                header.get("num_boxes").int("num_boxes")
            );
            check_eq!(
                problems,
                format!("{place}: header.num_rows"),
                p.grid.rows() as i64,
                header.get("num_rows").int("num_rows")
            );
            &p.grid
        }
        other => {
            problems.push(format!("{place}: not decoded: {}", short(other)));
            return;
        }
    };

    check_eq!(
        problems,
        format!("{place}: rows"),
        grid.rows() as i64,
        item.get("rows").int("rows")
    );
    check_eq!(
        problems,
        format!("{place}: cols"),
        grid.columns() as i64,
        item.get("cols").int("cols")
    );
    check_eq!(
        problems,
        format!("{place}: dtype"),
        Some("u8"),
        item.get("dtype").as_str()
    );
    check_eq!(
        problems,
        format!("{place}: raw_sha256"),
        common::sha256_hex(grid.levels()),
        item.get("raw_sha256").as_str().unwrap_or_default()
    );
    let mut histogram: BTreeMap<String, i64> = BTreeMap::new();
    for &level in grid.levels() {
        *histogram.entry(level.to_string()).or_default() += 1;
    }
    let golden_histogram: BTreeMap<String, i64> = match item.get("histogram") {
        Json::Obj(members) => members
            .iter()
            .map(|(k, v)| (k.clone(), v.int("histogram count")))
            .collect(),
        _ => BTreeMap::new(),
    };
    check_eq!(
        problems,
        format!("{place}: histogram"),
        histogram,
        golden_histogram
    );

    let physical = item.get("physical");
    let levels = DataLevels::for_packet(&product.description, code);
    let Some(levels) = levels else {
        problems.push(format!(
            "{place}: no data level mapping, MetPy physical {physical:?}"
        ));
        return;
    };
    if code == 18 && physical.is_null() {
        // MetPy maps no packet 18 levels. The decoder uses the 8-level rate
        // code of ICD 2620003AE section 30.2.1: codes 0-6 are the lower
        // bounds 0.0, 0.1, 0.3, 0.5, 1.0, 2.0, 4.0 in/h and code 7 is ND.
        let values = grid.values(&levels);
        if let Err(e) = check_values_accessors(grid, &levels, &values) {
            problems.push(format!("{place}: {e}"));
        }
        const RATES: [f32; 7] = [0.0, 0.1, 0.3, 0.5, 1.0, 2.0, 4.0];
        for (&level, &value) in grid.levels().iter().zip(&values) {
            let expected = RATES.get(usize::from(level)).copied();
            let ok = match expected {
                Some(rate) => value == rate,
                None => level == 7 && value.is_nan(),
            };
            if !ok {
                problems.push(format!("{place}: level {level} maps to {value}"));
                break;
            }
        }
        if levels.units() != Some("in h-1") {
            problems.push(format!("{place}: units {:?}", levels.units()));
        }
        counts.unmapped_checked += 1;
        return;
    }
    if physical.is_null() && matches!(product.description.product_code, 53 | 87) {
        // Weak Echo Region and combined shear (MetPy reads them with default
        // metadata): every level present is the value of its threshold
        // halfword `31 + N`, read here
        // per Figure 3-6 sheet 6 Note 1 (low byte; bit 14, 13 or 12 divides by
        // 100, 20 or 10; bit 8 negates), or a flag where bit 15 marks a code.
        let desc = &product.description;
        let mut present: Vec<u8> = grid.levels().to_vec();
        present.sort_unstable();
        present.dedup();
        for level in present {
            let raw = desc.halfword(31 + usize::from(level)).unwrap();
            let decoded = levels.level(u16::from(level));
            let ok = if raw & 0x8000 != 0 {
                matches!(decoded, Level::Flag(_))
            } else {
                let mut value = f64::from(raw & 0xFF);
                if raw & 0x4000 != 0 {
                    value /= 100.0;
                } else if raw & 0x2000 != 0 {
                    value /= 20.0;
                } else if raw & 0x1000 != 0 {
                    value /= 10.0;
                }
                if raw & 0x0100 != 0 {
                    value = -value;
                }
                decoded == Level::Value(value)
            };
            if !ok {
                problems.push(format!(
                    "{place}: level {level} (halfword {raw:#06x}) decoded as {decoded:?}"
                ));
            }
        }
        counts.unmapped_checked += 1;
        return;
    }
    if physical.is_null() {
        problems.push(format!(
            "{place}: MetPy maps no physical values, decoder maps {:?}",
            levels.encoding()
        ));
        return;
    }
    let values = grid.values(&levels);
    if let Err(e) = check_values_accessors(grid, &levels, &values) {
        problems.push(format!("{place}: {e}"));
    }
    let decoded = PhysicalSummary::of_f32(&values);
    for mismatch in decoded.mismatches(&PhysicalSummary::from_golden(physical)) {
        problems.push(format!("{place}: physical {mismatch}"));
    }
    counts.physical_checked += 1;
    counts
        .physical_products
        .insert(product.description.product_code);
}

/// `values` (from [`RasterGrid::values`]) and [`RasterGrid::level_at`] agree
/// with [`DataLevels::level`] for every cell.
fn check_values_accessors(
    grid: &RasterGrid,
    levels: &DataLevels,
    values: &[f32],
) -> Result<(), String> {
    if values.len() != grid.levels().len() {
        return Err(format!(
            "{} values for {} levels",
            values.len(),
            grid.levels().len()
        ));
    }
    for (i, (&value, &level)) in values.iter().zip(grid.levels()).enumerate() {
        let (row, column) = (i / grid.columns(), i % grid.columns());
        let meaning = levels.level(u16::from(level));
        let expected = meaning.value().map_or(f32::NAN, |v| v as f32);
        if value.to_bits() != expected.to_bits() {
            return Err(format!(
                "value at {row}, {column} is {value}, level {level} means {meaning:?}"
            ));
        }
        if grid.level_at(row, column, levels) != Some(meaning) {
            return Err(format!(
                "level_at({row}, {column}) differs from level {level}"
            ));
        }
    }
    if grid.level_at(grid.rows(), 0, levels).is_some()
        || grid.level_at(0, grid.columns(), levels).is_some()
    {
        return Err("level_at outside the grid returned a level".into());
    }
    Ok(())
}

/// `rows`, `columns`, `levels`, `row`, `get` and `iter_rows` describe the same grid.
fn check_grid_accessors(grid: &RasterGrid) -> Result<(), String> {
    let (rows, columns) = (grid.rows(), grid.columns());
    if grid.levels().len() != rows * columns {
        return Err(format!(
            "{} levels for {rows} x {columns}",
            grid.levels().len()
        ));
    }
    if grid.iter_rows().len() != rows {
        return Err(format!(
            "iter_rows yields {} rows, expected {rows}",
            grid.iter_rows().len()
        ));
    }
    let mut joined = Vec::with_capacity(rows * columns);
    for (r, row) in grid.iter_rows().enumerate() {
        if row.len() != columns || grid.row(r) != Some(row) {
            return Err(format!("row {r} differs between iter_rows and row()"));
        }
        for (c, &level) in row.iter().enumerate() {
            if grid.get(r, c) != Some(level) {
                return Err(format!("get({r}, {c}) differs from row {r}"));
            }
        }
        joined.extend_from_slice(row);
    }
    if joined != grid.levels() {
        return Err("rows joined differ from levels()".into());
    }
    if grid.row(rows).is_some() || grid.get(rows, 0).is_some() || grid.get(0, columns).is_some() {
        return Err("out-of-range row or cell returned a value".into());
    }
    Ok(())
}
