//! Raster packet family (Task L3.3): Raster Data Packet (0xBA07, 0xBA0F, ICD
//! 2620001 Figure 3-11), Digital Precipitation Data Array (17, Figure 3-11a),
//! Precipitation Rate Data Array (18, Figure 3-11b) and Digital Raster Data
//! Array (33, Figure 3-11d), against the real Level III corpus
//! (`testdata/level3/manifest.toml`) and its golden JSON
//! (`testdata/level3/golden/<id>.json`, generated by `tools/level3_golden.py`).
//!
//! Golden raster values come from MetPy 1.7.1 `Level3File`: the level grid of
//! each packet (`raw_sha256` of the row-major `u8` levels, `histogram`, `rows` x
//! `cols`) and, for products MetPy maps, a summary of `map_data` physical values.
//! Packet header fields come from the independent ICD walker in the golden tool.
//!
//! Physical values: data-level to physical mapping belongs to `src/levels.rs`
//! (radial family), which this branch does not have. [`physical_value`] is a
//! test-side reading of the two encodings the raster products in the corpus use
//! (`docs/level3/reference.md` section 5): **T16** (16 threshold halfwords
//! 31-46, MetPy `LegacyMapper`) and **DPA** (product 81, MetPy
//! `PrecipArrayMapper`). It checks decoded levels plus decoded halfwords against
//! MetPy's physical summaries.
//!
//! Corpus coverage: 0xBA07 in 26 files, 17 in 4, 18 in 4. No real sample of
//! 0xBA0F or 33 exists (reference section 7), so those codes are decoded by the
//! same code paths but have no corpus check. MetPy cannot read one raster file,
//! `l3-fws-sup-19950517-2304` (product 82); it is checked against an ICD
//! reading of its bytes in [`product_82_precipitation_rate_array_matches_icd_reading`].

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod common;

use std::collections::BTreeMap;

use common::{Entry, Json};
use recast_radar_io_level3::packets::raster::{RasterGrid, RasterHeader};
use recast_radar_io_level3::{Level3Error, Level3Product, Packet, decode_product};

/// Packet codes of the raster family.
const FAMILY_CODES: [u16; 5] = [0xBA07, 0xBA0F, 17, 18, 33];

/// Files MetPy cannot read that contain raster packets; each is checked by its
/// own ICD-based test below.
const ICD_CHECKED: [&str; 1] = ["l3-fws-sup-19950517-2304"];

/// Records a mismatch between a decoded value and its golden value.
macro_rules! check_eq {
    ($problems:expr, $what:expr, $decoded:expr, $golden:expr $(,)?) => {{
        let (decoded, golden) = (&$decoded, &$golden);
        if decoded != golden {
            $problems.push(format!(
                "{}: decoded {:?}, golden {:?}",
                $what, decoded, golden
            ));
        }
    }};
}

#[derive(Default, Debug)]
struct Counts {
    /// Files per family packet code.
    files: BTreeMap<u16, usize>,
    /// Decoded packets per family packet code.
    packets: BTreeMap<u16, usize>,
    /// Packets whose level grid was compared with MetPy's.
    grids_checked: usize,
    /// Packets whose physical summary was compared with MetPy's.
    physical_checked: usize,
}

#[test]
fn raster_packets_match_golden() {
    let mut counts = Counts::default();
    let mut failures = Vec::new();
    for entry in common::level3_manifest() {
        let golden = entry.golden();
        let expected = golden_family_counts(&golden);
        if expected.is_empty() {
            continue;
        }
        for code in expected.keys() {
            *counts.files.entry(*code).or_default() += 1;
        }
        let problems = check_file(&entry, &golden, &expected, &mut counts);
        if !problems.is_empty() {
            failures.push(format!("{}:\n    {}", entry.id, problems.join("\n    ")));
        }
    }
    assert!(
        failures.is_empty(),
        "{} files differ from golden:\n{}",
        failures.len(),
        failures.join("\n")
    );
    eprintln!("{counts:?}");
    // Every raster packet code with a real sample was decoded and compared.
    assert_eq!(counts.files.get(&0xBA07), Some(&26));
    assert_eq!(counts.files.get(&17), Some(&4));
    assert_eq!(counts.files.get(&18), Some(&4));
    // Packet 18: 40 layers of the three DPA files MetPy reads, plus product 82.
    let packets: Vec<(u16, usize)> = counts.packets.iter().map(|(c, n)| (*c, *n)).collect();
    assert_eq!(packets, [(17, 4), (18, 41), (0xBA07, 26)]);
    // Every packet in a file MetPy reads: 26 + 4 + 40 level grids, and physical
    // values for the 0xBA07 and 17 packets (MetPy maps no packet 18).
    assert_eq!(counts.grids_checked, 70);
    assert_eq!(counts.physical_checked, 30);
}

/// Product 82 (Supplemental Precipitation Data) from KFWS 1995: MetPy 1.7.1
/// raises `UnicodeDecodeError` on it (it expects a stand-alone tabular product),
/// so the expected values are an ICD reading of the file's own bytes.
///
/// The symbology block is at halfword 60 (byte 120 of the message); layer 0 (90
/// bytes) holds one packet 18 whose header is `00 12` (code 18), `00 00 00 00`
/// (two spares), `00 0d` (13 LFM boxes per row), `00 0d` (13 rows), followed by
/// 13 rows of `INT*2` byte count and 4-bit run / 4-bit level bytes (Figure
/// 3-11b). For example row 0 is `00 04 47 40 57 00`: 4 x level 7, 4 x level 0,
/// 5 x level 7, and a zero pad byte (run 0). The grid below expands every row
/// that way; each expands to exactly 13 boxes. Layer 1 holds packet 1 (text family).
#[test]
fn product_82_precipitation_rate_array_matches_icd_reading() {
    const EXPECTED: [[u8; 13]; 13] = [
        [7, 7, 7, 7, 0, 0, 0, 0, 7, 7, 7, 7, 7],
        [7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 7],
        [7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7],
        [7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7],
        [0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 7],
        [7, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 7],
        [7, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 7, 7],
        [7, 7, 0, 0, 3, 0, 0, 0, 0, 0, 0, 7, 7],
        [7, 7, 7, 7, 0, 0, 0, 0, 0, 7, 7, 7, 7],
    ];
    let entry = entry("l3-fws-sup-19950517-2304");
    assert_eq!(entry.golden().get("metpy").as_str(), Some("unsupported"));
    let product = decode_product(&entry.bytes()).unwrap();
    assert_eq!(product.description.product_code, 82);
    assert_eq!(product.description.symbology_offset, 60);
    let layers = &product.symbology.as_ref().unwrap().layers;
    assert_eq!(layers.len(), 2);
    assert_eq!(layers[0].len(), 1);
    let Packet::Raster(packet) = &layers[0][0] else {
        panic!(
            "layer 0: expected a decoded packet 18, got {:?}",
            layers[0][0]
        );
    };
    assert_eq!(packet.code, 18);
    assert_eq!(packet.code(), 18);
    assert_eq!(
        packet.header,
        RasterHeader::PrecipitationRate { spares: [0, 0] }
    );
    assert_eq!(packet.grid.rows(), 13);
    assert_eq!(packet.grid.columns(), 13);
    let rows: Vec<&[u8]> = packet.grid.iter_rows().collect();
    let expected: Vec<&[u8]> = EXPECTED.iter().map(|row| row.as_slice()).collect();
    assert_eq!(rows, expected);
    check_grid_accessors(&packet.grid).unwrap();
}

/// Real raster packets with one header field or run byte changed are rejected
/// with [`Level3Error::InvalidPacket`], and no single-byte change to a real
/// packet's header or first rows panics.
#[test]
fn corrupted_raster_packets_are_rejected_without_panic() {
    // KTLX 2013 composite reflectivity: layer 0 is one 0xBA07 packet.
    let ncr = RealPacket::locate("l3-tlx-ncr-20130520-2016", 0, 0xBA07);
    // Packing descriptor (packet bytes 20-21) other than 2.
    assert_invalid(&ncr.with(20, &[0x00, 0x03]), 0xBA07);
    // First row's first run shortened or lengthened by one: rows differ in width.
    let first_run = ncr.packet()[24];
    let changed = if first_run >> 4 == 15 {
        first_run - 0x10
    } else {
        first_run + 0x10
    };
    assert_invalid(&ncr.with(24, &[changed]), 0xBA07);

    // KTLX 2013 digital precipitation array: layer 0 is packet 17, layer 1 packet 18.
    let dpa17 = RealPacket::locate("l3-tlx-dpa-20130520-2016", 0, 17);
    let dpa18 = RealPacket::locate("l3-tlx-dpa-20130520-2016", 1, 18);
    // LFM boxes per row (packet bytes 6-7) no longer matching the row contents.
    for boxes in [0u16, 130, 132, 0xFFFF] {
        assert_invalid(&dpa17.with(6, &boxes.to_be_bytes()), 17);
        assert_invalid(&dpa18.with(6, &boxes.to_be_bytes()), 18);
    }

    let mut panics = Vec::new();
    for real in [&ncr, &dpa17, &dpa18] {
        let limit = real.len.min(160);
        for i in 0..limit {
            for value in [0x00, 0x11, 0xFF] {
                let mutated = real.with(i, &[value]);
                if std::panic::catch_unwind(|| decode_product(&mutated)).is_err() {
                    panics.push(format!("{} packet byte {i} = {value:#04x}", real.id));
                }
            }
        }
    }
    assert!(panics.is_empty(), "panicked:\n{}", panics.join("\n"));
}

/// Every header field is read from its own ICD offset. The corpus cannot show
/// this on its own: in every real raster packet I start equals J start and X
/// scale equals Y scale. Distinct values written into real headers must come
/// back in exactly the matching fields, with the grid unchanged.
#[test]
fn raster_header_fields_come_from_their_icd_offsets() {
    let ncr = RealPacket::locate("l3-tlx-ncr-20130520-2016", 0, 0xBA07);
    let Packet::Raster(original) = ncr.decoded(&ncr.bytes) else {
        unreachable!()
    };
    // Figure 3-11 halfwords 2-9: op flags, I start, J start, X scale integer and
    // fraction, Y scale integer and fraction.
    let values: [u16; 8] = [
        0x8001, 0x00C2, 0xFFFD, 0x0007, 0x0003, 0x0011, 0x0005, 0x0013,
    ];
    let patch: Vec<u8> = values.iter().flat_map(|v| v.to_be_bytes()).collect();
    let Packet::Raster(patched) = ncr.decoded(&ncr.with(2, &patch)) else {
        panic!("patched 0xBA07 packet not decoded");
    };
    assert_eq!(
        patched.header,
        RasterHeader::RasterData {
            op_flags: [0x8001, 0x00C2],
            i_start: -3,
            j_start: 7,
            x_scale: 3,
            x_scale_fraction: 17,
            y_scale: 5,
            y_scale_fraction: 19,
            packing: 2,
        }
    );
    assert_eq!(patched.grid, original.grid);

    // Figure 3-11a/b halfwords 2-3: the two spares.
    for (layer, code) in [(0, 17), (1, 18)] {
        let real = RealPacket::locate("l3-tlx-dpa-20130520-2016", layer, code);
        let original = real.decoded(&real.bytes);
        let patched = real.decoded(&real.with(2, &[0x12, 0x34, 0x56, 0x78]));
        match (original, patched) {
            (Packet::DigitalPrecip(original), Packet::DigitalPrecip(patched)) => {
                assert_eq!(original.spares, [0, 0]);
                assert_eq!(patched.spares, [0x1234, 0x5678]);
                assert_eq!(patched.grid, original.grid);
            }
            (Packet::Raster(original), Packet::Raster(patched)) => {
                assert_eq!(
                    original.header,
                    RasterHeader::PrecipitationRate { spares: [0, 0] }
                );
                assert_eq!(
                    patched.header,
                    RasterHeader::PrecipitationRate {
                        spares: [0x1234, 0x5678]
                    }
                );
                assert_eq!(patched.grid, original.grid);
            }
            other => panic!("packet {code}: unexpected variants {other:?}"),
        }
    }
}

/// A packet inside a real, uncompressed, unwrapped corpus file.
struct RealPacket {
    id: &'static str,
    bytes: Vec<u8>,
    /// Symbology layer holding the packet (as its only packet).
    layer: usize,
    /// File offset of the packet code.
    offset: usize,
    /// Packet length in bytes.
    len: usize,
}

impl RealPacket {
    /// The first packet of symbology layer `layer`, which must have `code`.
    fn locate(id: &'static str, layer: usize, code: u16) -> Self {
        let entry = entry(id);
        let golden = entry.golden();
        let framing = golden.get("framing");
        assert_eq!(framing.get("zlib_frames").int("zlib_frames"), 0);
        assert!(framing.get("trailer").is_null());
        assert_eq!(
            golden.get("compression").get("bzip2").as_bool(),
            Some(false)
        );
        let bytes = entry.bytes();
        let message_start = bytes.len()
            - usize::try_from(framing.get("message_bytes").int("message_bytes")).unwrap();
        let symbology = golden.get("blocks").get("symbology");
        let halfwords = golden.get("halfwords").items();
        let offset_hw = (halfwords[54].int("hw55") << 16) | halfwords[55].int("hw56");
        // Block header (divider, ID, length, layer count) is 10 bytes; each layer
        // header (divider, length) is 6 bytes.
        let mut offset = message_start + 2 * usize::try_from(offset_hw).unwrap() + 10;
        let layers = symbology.get("layers").items();
        for skipped in &layers[..layer] {
            offset += 6 + usize::try_from(skipped.get("length").int("layer length")).unwrap();
        }
        offset += 6;
        assert_eq!(
            u16::from_be_bytes([bytes[offset], bytes[offset + 1]]),
            code,
            "{id}: packet code at file byte {offset}"
        );
        assert_eq!(layers[layer].get("packets").items().len(), 1);
        let len = usize::try_from(layers[layer].get("length").int("layer length")).unwrap();
        let located = Self {
            id,
            bytes,
            layer,
            offset,
            len,
        };
        // The unmodified file decodes, with this packet decoded.
        let packet = located.decoded(&located.bytes);
        assert!(
            matches!(packet, Packet::Raster(_) | Packet::DigitalPrecip(_)),
            "{id}: layer {layer} packet not decoded: {packet:?}"
        );
        located
    }

    /// The packet decoded from `file` (this file, possibly patched).
    fn decoded(&self, file: &[u8]) -> Packet {
        let product = decode_product(file).unwrap_or_else(|e| panic!("{}: {e}", self.id));
        product
            .symbology
            .unwrap()
            .layers
            .swap_remove(self.layer)
            .swap_remove(0)
    }

    fn packet(&self) -> &[u8] {
        &self.bytes[self.offset..self.offset + self.len]
    }

    /// The file with `patch` written at packet byte `at`.
    fn with(&self, at: usize, patch: &[u8]) -> Vec<u8> {
        let mut bytes = self.bytes.clone();
        bytes[self.offset + at..self.offset + at + patch.len()].copy_from_slice(patch);
        bytes
    }
}

fn assert_invalid(bytes: &[u8], code: u16) {
    match decode_product(bytes) {
        Err(Level3Error::InvalidPacket { code: found, .. }) if found == code => {}
        other => panic!(
            "expected InvalidPacket for packet {code}, got {}",
            match other {
                Ok(_) => "a decoded product".to_string(),
                Err(e) => format!("error: {e}"),
            }
        ),
    }
}

fn entry(id: &str) -> Entry {
    common::level3_manifest()
        .into_iter()
        .find(|e| e.id == id)
        .unwrap_or_else(|| panic!("{id} not in the manifest"))
}

/// Family packet codes and their counts in the golden walker's block structure.
fn golden_family_counts(golden: &Json) -> BTreeMap<u16, usize> {
    let blocks = golden.get("blocks");
    let mut lists: Vec<&Json> = Vec::new();
    let symbology = blocks.get("symbology");
    lists.extend(
        symbology
            .get("layers")
            .items()
            .iter()
            .map(|l| l.get("packets")),
    );
    lists.extend(
        symbology
            .get("nested")
            .items()
            .iter()
            .map(|n| n.get("packets")),
    );
    lists.extend(
        blocks
            .get("graphic")
            .get("pages")
            .items()
            .iter()
            .map(|p| p.get("packets")),
    );
    lists.push(blocks.get("cell_trend").get("packets"));
    let mut counts = BTreeMap::new();
    for list in lists {
        for code in list.items() {
            let code = u16::try_from(code.int("packet code")).unwrap();
            if FAMILY_CODES.contains(&code) {
                *counts.entry(code).or_default() += 1;
            }
        }
    }
    counts
}

fn check_file(
    entry: &Entry,
    golden: &Json,
    expected: &BTreeMap<u16, usize>,
    counts: &mut Counts,
) -> Vec<String> {
    let mut problems = Vec::new();
    let bytes = entry.bytes();
    let product = match decode_product(&bytes) {
        Ok(product) => product,
        Err(e) => return vec![format!("decode failed: {e}")],
    };

    // Every family packet anywhere in the product is decoded.
    let mut decoded = BTreeMap::new();
    for (place, packet) in all_packets(&product) {
        let code = packet.code();
        if !FAMILY_CODES.contains(&code) {
            continue;
        }
        *decoded.entry(code).or_default() += 1;
        match packet {
            Packet::Raster(p) if code != 17 => {
                if let Err(e) = check_grid_accessors(&p.grid) {
                    problems.push(format!("{place}: {e}"));
                }
            }
            Packet::DigitalPrecip(p) if code == 17 => {
                if let Err(e) = check_grid_accessors(&p.grid) {
                    problems.push(format!("{place}: {e}"));
                }
            }
            other => problems.push(format!(
                "{place}: packet {code} not decoded: {}",
                short(other)
            )),
        }
    }
    check_eq!(problems, "family packet counts", decoded, *expected);
    for (code, n) in &decoded {
        *counts.packets.entry(*code).or_default() += n;
    }

    let data = golden.get("data");
    if data.is_null() {
        if !ICD_CHECKED.contains(&entry.id.as_str()) {
            problems.push(format!(
                "MetPy status {:?} and no ICD-based test for this file",
                golden.get("metpy").as_str()
            ));
        }
        return problems;
    }
    let mapper = golden.get("metpy_detail").get("mapper").as_str();
    let symbology_family = product.symbology.as_ref().map_or(0, |s| {
        s.layers
            .iter()
            .flatten()
            .filter(|p| FAMILY_CODES.contains(&p.code()))
            .count()
    });
    let mut compared = 0;
    for item in data.items() {
        let code = u16::try_from(item.get("packet").int("data.packet")).unwrap();
        if !FAMILY_CODES.contains(&code) {
            continue;
        }
        compared += 1;
        let layer = usize::try_from(item.get("layer").int("data.layer")).unwrap();
        let index = usize::try_from(item.get("index").int("data.index")).unwrap();
        let place = format!("layer {layer} packet {index} (code {code})");
        if let Some(error) = item.get("error").as_str() {
            problems.push(format!("{place}: golden has no grid: {error}"));
            continue;
        }
        let Some(packet) = product
            .symbology
            .as_ref()
            .and_then(|s| s.layers.get(layer))
            .and_then(|l| l.get(index))
        else {
            problems.push(format!("{place}: no such decoded packet"));
            continue;
        };
        let before = problems.len();
        check_packet(
            &product,
            packet,
            code,
            item,
            mapper,
            &place,
            counts,
            &mut problems,
        );
        if problems.len() == before {
            counts.grids_checked += 1;
        }
    }
    check_eq!(
        problems,
        "symbology family packets compared with MetPy",
        compared,
        symbology_family
    );
    problems
}

/// Every packet in the symbology layers and graphic pages, with its place.
fn all_packets(product: &Level3Product) -> Vec<(String, &Packet)> {
    let mut out = Vec::new();
    if let Some(symbology) = &product.symbology {
        for (l, layer) in symbology.layers.iter().enumerate() {
            for (i, packet) in layer.iter().enumerate() {
                out.push((format!("symbology layer {l} packet {i}"), packet));
            }
        }
    }
    if let Some(graphic) = &product.graphic {
        for page in &graphic.pages {
            for (i, packet) in page.packets.iter().enumerate() {
                out.push((format!("graphic page {} packet {i}", page.number), packet));
            }
        }
    }
    out
}

fn short(packet: &Packet) -> String {
    match packet {
        Packet::Unknown { code, bytes } => {
            format!("Unknown {{ code: {code}, {} bytes }}", bytes.len())
        }
        other => format!("variant for code {}", other.code()),
    }
}

#[allow(clippy::too_many_arguments)]
fn check_packet(
    product: &Level3Product,
    packet: &Packet,
    code: u16,
    item: &Json,
    mapper: Option<&str>,
    place: &str,
    counts: &mut Counts,
    problems: &mut Vec<String>,
) {
    let header = item.get("header");
    let grid = match packet {
        Packet::Raster(p) => {
            check_eq!(problems, format!("{place}: code"), p.code, code);
            match (code, p.header) {
                (
                    0xBA07 | 0xBA0F,
                    RasterHeader::RasterData {
                        op_flags,
                        i_start,
                        j_start,
                        x_scale,
                        x_scale_fraction,
                        y_scale,
                        y_scale_fraction,
                        packing,
                    },
                ) => {
                    let flags: Vec<i64> = header
                        .get("op_flags")
                        .items()
                        .iter()
                        .map(|f| f.int("op_flags"))
                        .collect();
                    check_eq!(
                        problems,
                        format!("{place}: op_flags"),
                        op_flags.map(i64::from).to_vec(),
                        flags
                    );
                    for (name, value) in [
                        ("i_start", i64::from(i_start)),
                        ("j_start", i64::from(j_start)),
                        ("x_scale_int", i64::from(x_scale)),
                        ("x_scale_frac", i64::from(x_scale_fraction)),
                        ("y_scale_int", i64::from(y_scale)),
                        ("y_scale_frac", i64::from(y_scale_fraction)),
                        ("packing", i64::from(packing)),
                        ("num_rows", p.grid.rows() as i64),
                    ] {
                        check_eq!(
                            problems,
                            format!("{place}: header.{name}"),
                            value,
                            header.get(name).int(name)
                        );
                    }
                }
                (18, RasterHeader::PrecipitationRate { .. }) => {
                    check_eq!(
                        problems,
                        format!("{place}: header.num_boxes"),
                        p.grid.columns() as i64,
                        header.get("num_boxes").int("num_boxes")
                    );
                    check_eq!(
                        problems,
                        format!("{place}: header.num_rows"),
                        p.grid.rows() as i64,
                        header.get("num_rows").int("num_rows")
                    );
                }
                (33, RasterHeader::DigitalRaster { .. }) => {
                    check_eq!(
                        problems,
                        format!("{place}: header.num_cells"),
                        p.grid.columns() as i64,
                        header.get("num_cells").int("num_cells")
                    );
                    check_eq!(
                        problems,
                        format!("{place}: header.num_rows"),
                        p.grid.rows() as i64,
                        header.get("num_rows").int("num_rows")
                    );
                }
                (_, other) => {
                    problems.push(format!(
                        "{place}: header {other:?} does not match code {code}"
                    ));
                    return;
                }
            }
            &p.grid
        }
        Packet::DigitalPrecip(p) if code == 17 => {
            check_eq!(problems, format!("{place}: code"), p.code, code);
            check_eq!(
                problems,
                format!("{place}: header.num_boxes"),
                p.grid.columns() as i64,
                header.get("num_boxes").int("num_boxes")
            );
            check_eq!(
                problems,
                format!("{place}: header.num_rows"),
                p.grid.rows() as i64,
                header.get("num_rows").int("num_rows")
            );
            &p.grid
        }
        other => {
            problems.push(format!("{place}: not decoded: {}", short(other)));
            return;
        }
    };

    check_eq!(
        problems,
        format!("{place}: rows"),
        grid.rows() as i64,
        item.get("rows").int("rows")
    );
    check_eq!(
        problems,
        format!("{place}: cols"),
        grid.columns() as i64,
        item.get("cols").int("cols")
    );
    check_eq!(
        problems,
        format!("{place}: dtype"),
        Some("u8"),
        item.get("dtype").as_str()
    );
    check_eq!(
        problems,
        format!("{place}: raw_sha256"),
        sha256_hex(grid.levels()),
        item.get("raw_sha256").as_str().unwrap_or_default()
    );
    let mut histogram: BTreeMap<String, i64> = BTreeMap::new();
    for &level in grid.levels() {
        *histogram.entry(level.to_string()).or_default() += 1;
    }
    let golden_histogram: BTreeMap<String, i64> = match item.get("histogram") {
        Json::Obj(members) => members
            .iter()
            .map(|(k, v)| (k.clone(), v.int("histogram count")))
            .collect(),
        _ => BTreeMap::new(),
    };
    check_eq!(
        problems,
        format!("{place}: histogram"),
        histogram,
        golden_histogram
    );

    let physical = item.get("physical");
    if physical.is_null() {
        return;
    }
    let encoding = match mapper {
        Some("LegacyMapper") => Encoding::T16,
        Some("PrecipArrayMapper") => Encoding::Dpa,
        other => {
            problems.push(format!(
                "{place}: no test mapping for MetPy mapper {other:?}"
            ));
            return;
        }
    };
    let halfwords = &product.description.halfwords;
    let values: Vec<f64> = grid
        .levels()
        .iter()
        .filter_map(|&level| physical_value(encoding, halfwords, level))
        .collect();
    let masked = grid.levels().len() - values.len();
    check_eq!(
        problems,
        format!("{place}: physical.finite"),
        values.len() as i64,
        physical.get("finite").int("finite")
    );
    check_eq!(
        problems,
        format!("{place}: physical.masked"),
        masked as i64,
        physical.get("masked").int("masked")
    );
    let summary = (!values.is_empty()).then(|| {
        let min = values.iter().copied().fold(f64::INFINITY, f64::min);
        let max = values.iter().copied().fold(f64::NEG_INFINITY, f64::max);
        let mean = values.iter().sum::<f64>() / values.len() as f64;
        [min, max, mean]
    });
    let golden_summary = ["min", "max", "mean"].map(|k| physical.get(k).as_f64());
    match summary {
        None => check_eq!(
            problems,
            format!("{place}: physical min/max/mean"),
            [None, None, None],
            golden_summary
        ),
        Some(values) => {
            for ((name, value), golden) in ["min", "max", "mean"]
                .iter()
                .zip(values)
                .zip(golden_summary)
            {
                let close = golden.is_some_and(|g| {
                    (value - g).abs() <= 1e-4 * value.abs().max(g.abs()).max(1e-9)
                });
                if !close {
                    problems.push(format!(
                        "{place}: physical.{name}: decoded {value}, golden {golden:?}"
                    ));
                }
            }
        }
    }
    counts.physical_checked += 1;
}

#[derive(Clone, Copy)]
enum Encoding {
    /// Halfword `31 + N` describes level `N` (reference section 5, T16).
    T16,
    /// Product 81: level `1..=254` is `hw31 / 10 + (N - 1) * hw32 / 1000` dBA
    /// (reference section 5, DPA); 0 and 255 have no value.
    Dpa,
}

/// Physical value of `level`, or `None` when the level is a code (below
/// threshold, no data, range folded, ...) rather than a value.
fn physical_value(encoding: Encoding, halfwords: &[u16], level: u8) -> Option<f64> {
    match encoding {
        Encoding::T16 => {
            let hw = *halfwords.get(30 + usize::from(level))?;
            if hw & 0x8000 != 0 {
                return None;
            }
            let mut value = f64::from(hw & 0xFF);
            if hw & 0x4000 != 0 {
                value /= 100.0;
            } else if hw & 0x2000 != 0 {
                value /= 20.0;
            } else if hw & 0x1000 != 0 {
                value /= 10.0;
            }
            if hw & 0x0100 != 0 {
                value = -value;
            }
            Some(value)
        }
        Encoding::Dpa => {
            if !(1..=254).contains(&level) {
                return None;
            }
            let minimum = f64::from(halfwords[30] as i16) / 10.0;
            let increment = f64::from(halfwords[31]) / 1000.0;
            Some(minimum + f64::from(level - 1) * increment)
        }
    }
}

/// `rows`, `columns`, `levels`, `row`, `get` and `iter_rows` describe the same grid.
fn check_grid_accessors(grid: &RasterGrid) -> Result<(), String> {
    let (rows, columns) = (grid.rows(), grid.columns());
    if grid.levels().len() != rows * columns {
        return Err(format!(
            "{} levels for {rows} x {columns}",
            grid.levels().len()
        ));
    }
    if grid.iter_rows().len() != rows {
        return Err(format!(
            "iter_rows yields {} rows, expected {rows}",
            grid.iter_rows().len()
        ));
    }
    let mut joined = Vec::with_capacity(rows * columns);
    for (r, row) in grid.iter_rows().enumerate() {
        if row.len() != columns || grid.row(r) != Some(row) {
            return Err(format!("row {r} differs between iter_rows and row()"));
        }
        for (c, &level) in row.iter().enumerate() {
            if grid.get(r, c) != Some(level) {
                return Err(format!("get({r}, {c}) differs from row {r}"));
            }
        }
        joined.extend_from_slice(row);
    }
    if joined != grid.levels() {
        return Err("rows joined differ from levels()".into());
    }
    if grid.row(rows).is_some() || grid.get(rows, 0).is_some() || grid.get(0, columns).is_some() {
        return Err("out-of-range row or cell returned a value".into());
    }
    Ok(())
}

/// SHA-256 (FIPS 180-4) as lowercase hex; the crate has no dev-dependencies.
fn sha256_hex(data: &[u8]) -> String {
    const K: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4,
        0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe,
        0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f,
        0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
        0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc,
        0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
        0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116,
        0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7,
        0xc67178f2,
    ];
    let mut h: [u32; 8] = [
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab,
        0x5be0cd19,
    ];
    let mut message = data.to_vec();
    message.push(0x80);
    while message.len() % 64 != 56 {
        message.push(0);
    }
    message.extend_from_slice(&(data.len() as u64 * 8).to_be_bytes());
    for block in message.chunks_exact(64) {
        let mut w = [0u32; 64];
        for (word, bytes) in w.iter_mut().zip(block.chunks_exact(4)) {
            *word = u32::from_be_bytes(bytes.try_into().unwrap());
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }
        let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut hh] = h;
        for i in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ (!e & g);
            let t1 = hh
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(K[i])
                .wrapping_add(w[i]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let t2 = s0.wrapping_add(maj);
            hh = g;
            g = f;
            f = e;
            e = d.wrapping_add(t1);
            d = c;
            c = b;
            b = a;
            a = t1.wrapping_add(t2);
        }
        for (state, add) in h.iter_mut().zip([a, b, c, d, e, f, g, hh]) {
            *state = state.wrapping_add(add);
        }
    }
    h.iter().map(|word| format!("{word:08x}")).collect()
}

#[test]
fn sha256_matches_known_digests() {
    assert_eq!(
        sha256_hex(b"abc"),
        "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
    );
    // Each committed raster file hashes to its manifest sha256 (multi-block input).
    for id in ["l3-tlx-dpa-20130520-2016", "l3-fws-sup-19950517-2304"] {
        let entry = entry(id);
        assert_eq!(sha256_hex(&entry.bytes()), entry.sha256, "{id}");
    }
}
