//! End-to-end tests of the `recast-radar` binary on real files.
//!
//! Expected values come from the Py-ART and xradar goldens in
//! `testdata/conformance/fm301` (generated by `tools/fm301_golden.py`), and
//! from the testdata manifest descriptions, whose counts were taken with
//! Py-ART and MetPy.

// A failed expectation in a test helper is a test failure.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::ffi::OsStr;
use std::fs;
use std::io::{BufRead, BufReader, Read, Write};
use std::net::TcpStream;
use std::path::{Path, PathBuf};
use std::process::{Command, Output, Stdio};

use serde_json::Value;

fn run<I, S>(args: I) -> Output
where
    I: IntoIterator<Item = S>,
    S: AsRef<OsStr>,
{
    Command::new(env!("CARGO_BIN_EXE_recast-radar"))
        .args(args)
        .output()
        .expect("run recast-radar")
}

fn fixture(id: &str) -> PathBuf {
    recast_radar_testdata::path(id).unwrap_or_else(|err| panic!("{err}"))
}

fn stdout(output: &Output) -> String {
    String::from_utf8_lossy(&output.stdout).into_owned()
}

fn stderr(output: &Output) -> String {
    String::from_utf8_lossy(&output.stderr).into_owned()
}

fn json(output: &Output) -> Value {
    assert!(output.status.success(), "{}", stderr(output));
    serde_json::from_slice(&output.stdout).expect("JSON output")
}

/// An empty directory for one test's output.
fn scratch(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("recast-radar-cli-{name}-{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).expect("create scratch directory");
    dir
}

fn golden(kind: &str, id: &str) -> Value {
    let path = recast_radar_testdata::workspace_root()
        .join("testdata/conformance/fm301")
        .join(kind)
        .join(format!("{id}.json"));
    serde_json::from_slice(&fs::read(&path).expect("read golden")).expect("parse golden")
}

const ESPDG: &str = "odim-espdg-20260707-1927-pvol-dbzh-vradh";

#[test]
fn help_names_every_command() {
    let output = run(["--help"]);
    assert!(output.status.success());
    let text = stdout(&output);
    for command in [
        "info", "dump", "render", "fetch", "validate", "bench", "convert", "publish", "serve",
    ] {
        assert!(
            text.contains(&format!("  {command}  ")),
            "{command}: {text}"
        );
    }
    let version = stdout(&run(["--version"]));
    assert_eq!(
        version.trim(),
        format!("recast-radar {}", env!("CARGO_PKG_VERSION"))
    );
}

#[test]
fn invalid_arguments_exit_with_status_2() {
    let output = run(["info"]);
    assert_eq!(output.status.code(), Some(2));
    let output = run([
        OsStr::new("dump"),
        OsStr::new("--sweep"),
        OsStr::new("99"),
        fixture(ESPDG).as_os_str(),
    ]);
    assert_eq!(output.status.code(), Some(2), "{}", stderr(&output));
    assert!(
        stderr(&output).contains("2 sweep(s)"),
        "{}",
        stderr(&output)
    );
}

/// Manifest: sweep 1 REF/ZDR/PHI/RHO/CFP and sweep 2 REF/VEL/SW, 480 of 720
/// radials each, VCP 212, Build 22.0.
#[test]
fn info_summarizes_a_trimmed_level2_volume() {
    let path = fixture("l2-ktlx-20240315-000217-trim");
    let output = run([path.as_os_str()]);
    // `info` is required: a bare file is not a command.
    assert_eq!(output.status.code(), Some(2));

    let output = run([OsStr::new("info"), path.as_os_str()]);
    assert!(output.status.success(), "{}", stderr(&output));
    let text = stdout(&output);
    for expected in [
        "NEXRAD Level II",
        "KTLX",
        "VCP 212",
        "2 sweeps, 960 rays",
        "DBZH ZDR PHIDP RHOHV CCORH",
        "DBZH VRADH WRADH",
    ] {
        assert!(text.contains(expected), "{expected}: {text}");
    }

    let report = json(&run([
        OsStr::new("info"),
        OsStr::new("--json"),
        path.as_os_str(),
    ]));
    let volume = &report["volumes"][0];
    assert_eq!(volume["site"], "KTLX");
    assert_eq!(volume["vcp"], 212);
    assert_eq!(volume["sweep_count"], 2);
    for sweep in volume["sweeps"].as_array().expect("sweeps") {
        assert_eq!(sweep["rays"], 480);
        assert!((sweep["fixed_angle_deg"].as_f64().unwrap_or(0.0) - 0.48).abs() < 0.01);
    }
}

/// Py-ART `aux_io.read_odim_h5`: 2 sweeps of 360 rays and 299 gates.
#[test]
fn info_json_agrees_with_pyart_on_an_odim_volume() {
    let pyart = golden("pyart", ESPDG);
    let report = json(&run([
        OsStr::new("info"),
        OsStr::new("--json"),
        fixture(ESPDG).as_os_str(),
    ]));
    assert_eq!(report["format"], "ODIM_H5");
    let volume = &report["volumes"][0];
    assert_eq!(volume["sweep_count"], pyart["radar"]["nsweeps"]);
    let sweeps = volume["sweeps"].as_array().expect("sweeps");
    for (sweep, reference) in sweeps
        .iter()
        .zip(pyart["radar"]["sweeps"].as_array().expect("sweeps"))
    {
        assert_eq!(sweep["rays"], reference["rays"]);
        assert_eq!(sweep["gates"], pyart["radar"]["ngates"]);
    }
}

#[test]
fn info_reads_every_committed_format() {
    for (id, format) in [
        ("l2-ktlx-19910605-162126-trim", "NEXRAD Level II"),
        ("odim-bejab-20190606-0000-pvol", "ODIM_H5"),
        ("cfrad1-xsapr-sgp-20110520-ppi-classic", "CfRadial 1"),
        ("dorade-cow2-20260521-225514-sur-head24", "DORADE"),
        ("dorade-noxp-20090610-003210-heads-zip", "DORADE"),
        ("jma-n5-20191012-090000-rs47773", "JMA GRIB2"),
        ("l3-byx-n0q-20150124-2106", "NEXRAD Level III"),
        ("l3-kdvn-20200810-1804-nst", "NEXRAD Level III"),
        (
            "l2chunk-kiwa-307-20260917-003629-002-i",
            "NEXRAD Level II records",
        ),
    ] {
        let report = json(&run([
            OsStr::new("info"),
            OsStr::new("--json"),
            fixture(id).as_os_str(),
        ]));
        assert_eq!(report["format"], format, "{id}");
    }
}

/// Manifest: TAKA, 26 sweeps of 512 radials.
#[test]
fn a_jma_station_is_chosen_with_station() {
    let path = fixture("jma-n5-20191012-090000-rs47773");
    let report = json(&run([
        OsStr::new("info"),
        OsStr::new("--json"),
        OsStr::new("--station"),
        OsStr::new("TAKA"),
        path.as_os_str(),
    ]));
    let volume = &report["volumes"][0];
    assert_eq!(volume["site"], "TAKA");
    assert_eq!(volume["sweep_count"], 26);
    for sweep in volume["sweeps"].as_array().expect("sweeps") {
        assert_eq!(sweep["rays"], 512);
    }
    let output = run([
        OsStr::new("info"),
        OsStr::new("--station"),
        OsStr::new("NOPE"),
        path.as_os_str(),
    ]);
    assert_eq!(output.status.code(), Some(1));
}

/// EUMETNET ORD serves a BEJAB scan as one file per moment; the file names
/// list the elevations (0.5 to 25 deg), so the merged volume has those 9
/// sweeps, each with both moments.
#[test]
fn info_merges_parts_of_one_scan() {
    let dbzh = fixture("odim-bejab-20260612-1450-dbzh");
    let vrad = fixture("odim-bejab-20260612-1450-vrad");
    let report = json(&run([
        OsStr::new("info"),
        OsStr::new("--merge"),
        OsStr::new("--json"),
        dbzh.as_os_str(),
        vrad.as_os_str(),
    ]));
    let volume = &report["volumes"][0];
    assert_eq!(volume["site"], "BEJAB");
    let sweeps = volume["sweeps"].as_array().expect("sweeps");
    let angles: Vec<f64> = sweeps
        .iter()
        .map(|sweep| (sweep["fixed_angle_deg"].as_f64().unwrap_or(f64::NAN) * 10.0).round() / 10.0)
        .collect();
    assert_eq!(angles, [0.5, 1.2, 2.1, 3.4, 4.8, 6.5, 9.0, 13.0, 25.0]);
    for sweep in sweeps {
        assert_eq!(sweep["fields"], serde_json::json!(["DBZH", "VRAD"]));
    }
    // Without --merge, several files are summarized one by one.
    let reports = json(&run([
        OsStr::new("info"),
        OsStr::new("--json"),
        dbzh.as_os_str(),
        vrad.as_os_str(),
    ]));
    assert_eq!(reports.as_array().map(Vec::len), Some(2));
}

/// Py-ART masks ODIM `nodata` and `undetect`; the unmasked gates are the
/// `values` of `dump`, with the same range.
#[test]
fn dump_field_statistics_agree_with_pyart() {
    let pyart = golden("pyart", ESPDG);
    let report = json(&run([
        OsStr::new("dump"),
        OsStr::new("--json"),
        OsStr::new("--field"),
        OsStr::new("dbzh"),
        fixture(ESPDG).as_os_str(),
    ]));
    let sweeps = report["volumes"][0]["sweeps"].as_array().expect("sweeps");
    let reference = pyart["fields"]["reflectivity_horizontal"]["per_sweep"]
        .as_array()
        .expect("per-sweep statistics");
    assert_eq!(sweeps.len(), reference.len());
    for (sweep, expected) in sweeps.iter().zip(reference) {
        let fields = sweep["fields"].as_array().expect("fields");
        assert_eq!(fields.len(), 1, "--field keeps only DBZH");
        let stats = &fields[0]["stats"];
        assert_eq!(stats["values"], expected["count_unmasked"]);
        assert_eq!(stats["min"].as_f64(), expected["min"].as_f64());
        assert_eq!(stats["max"].as_f64(), expected["max"].as_f64());
        let mean = stats["mean"].as_f64().expect("mean");
        let expected_mean = expected["mean"].as_f64().expect("mean");
        assert!(
            (mean - expected_mean).abs() < 1e-6,
            "{mean} vs {expected_mean}"
        );
    }
}

#[test]
fn dump_data_rows_have_the_field_shape() {
    let report = json(&run([
        OsStr::new("dump"),
        OsStr::new("--json"),
        OsStr::new("--sweep"),
        OsStr::new("1"),
        OsStr::new("--field"),
        OsStr::new("VRADH"),
        OsStr::new("--data"),
        fixture(ESPDG).as_os_str(),
    ]));
    let sweeps = report["volumes"][0]["sweeps"].as_array().expect("sweeps");
    assert_eq!(sweeps.len(), 1);
    assert_eq!(sweeps[0]["index"], 1);
    let field = &sweeps[0]["fields"][0];
    let rows = field["data"].as_array().expect("data rows");
    assert_eq!(rows.len(), 360);
    assert!(
        rows.iter()
            .all(|row| row.as_array().map(Vec::len) == Some(299))
    );
    let valid = rows
        .iter()
        .flat_map(|row| row.as_array().into_iter().flatten())
        .filter(|value| value.is_number())
        .count();
    assert_eq!(valid as u64, field["stats"]["values"].as_u64().unwrap_or(0));

    // The text form carries the same metadata.
    let output = run([
        OsStr::new("dump"),
        OsStr::new("--sweep"),
        OsStr::new("0"),
        fixture(ESPDG).as_os_str(),
    ]);
    assert!(output.status.success());
    let text = stdout(&output);
    assert!(text.contains("field DBZH:"), "{text}");
    assert!(text.contains("instrument_name: ESPDG"), "{text}");
}

/// Level III Storm Tracking Information (product 58): the headers are JSON
/// objects, and every storm-id packet is there with MetPy's position (the
/// tracking golden, `tools/track_golden.py`: MetPy `Level3File` x/y in km).
#[test]
fn dump_level3_gives_packets_and_pages_as_json() {
    let report = json(&run([
        OsStr::new("dump"),
        OsStr::new("--json"),
        fixture("l3-kdvn-20200810-1804-nst").as_os_str(),
    ]));
    let level3 = &report["level3"];
    assert_eq!(level3["message_header"]["code"], 58);
    assert_eq!(level3["description"]["product_code"], 58);
    assert_eq!(level3["description"]["vcp"], 212);
    assert_eq!(level3["text_header"]["awips_id"], "NSTDVN");

    let mut positions = std::collections::HashMap::new();
    for layer in level3["symbology"]["layers"].as_array().expect("layers") {
        for packet in layer.as_array().expect("packets") {
            assert!(packet["code"].as_str().is_some_and(|c| c.starts_with("0x")));
            for storm in packet["packet"]["StormIds"]
                .as_array()
                .into_iter()
                .flatten()
            {
                let at = |key: &str| storm[key].as_f64().expect("position") / 4.0;
                positions.insert(
                    storm["id"].as_str().expect("id").to_owned(),
                    (at("i"), at("j")),
                );
            }
        }
    }
    let golden: Value = serde_json::from_slice(
        &fs::read(
            recast_radar_testdata::workspace_root().join("testdata/golden/track/tracking.json"),
        )
        .expect("read golden"),
    )
    .expect("parse golden");
    let volume = golden["kdvn"]["volumes"]
        .as_array()
        .expect("volumes")
        .iter()
        .find(|v| v["sti"] == "l3-kdvn-20200810-1804-nst")
        .expect("golden volume");
    let storms = volume["storms"].as_array().expect("storms");
    assert_eq!(positions.len(), storms.len());
    for storm in storms {
        let id = storm["id"].as_str().expect("id");
        let expected = (
            storm["east_km"].as_f64().expect("east"),
            storm["north_km"].as_f64().expect("north"),
        );
        assert_eq!(positions.get(id), Some(&expected), "storm {id}");
    }

    // The graphic pages' text packets and the tabular pages.
    let pages = level3["graphic"]["pages"]
        .as_array()
        .expect("graphic pages");
    assert_eq!(pages.len(), 6);
    let first_line = pages[0]["packets"][0]["packet"]["text"]
        .as_str()
        .expect("text");
    assert!(first_line.contains("STORM ID"), "{first_line}");
    let tabular = level3["tabular"]["pages"][0][1]
        .as_str()
        .expect("tabular line");
    assert!(tabular.contains("NUMBER OF STORM CELLS  45"), "{tabular}");
}

/// Level II metadata messages are JSON objects too.
#[test]
fn dump_level2_metadata_messages_are_json_objects() {
    let report = json(&run([
        OsStr::new("dump"),
        OsStr::new("--json"),
        OsStr::new("--sweep"),
        OsStr::new("0"),
        fixture("l2-ktlx-20240315-000217-trim").as_os_str(),
    ]));
    let nexrad = &report["volumes"][0]["format_metadata"]["nexrad"];
    // VCP 212 and Build 22, as the manifest description (from Py-ART and
    // MetPy) gives them.
    assert_eq!(nexrad["vcp"]["pattern_number"], 212);
    assert_eq!(nexrad["build"]["RdaBuild"], 2200);
    assert!(nexrad["rda_status"].is_object());
    assert!(nexrad["adaptation"].is_object());
    let cuts = nexrad["vcp"]["cuts"].as_array().expect("cuts");
    assert_eq!(
        cuts.len(),
        nexrad["vcp"]["number_of_cuts"].as_u64().expect("count") as usize
    );
}

/// xradar `open_odim_datatree` (first_dim="auto"): the sweep groups and
/// their dimensions.
#[test]
fn dump_fm301_has_the_xradar_groups() {
    let xradar = golden("xradar", ESPDG);
    let tree = json(&run([
        OsStr::new("dump"),
        OsStr::new("--fm301"),
        OsStr::new("--json"),
        fixture(ESPDG).as_os_str(),
    ]));
    fn collect(group: &Value, parent: &str, out: &mut Vec<(String, Value)>) {
        let name = group["name"].as_str().unwrap_or("?");
        let path = if name == "/" {
            "/".to_owned()
        } else {
            format!("{}/{name}", parent.trim_end_matches('/'))
        };
        out.push((path.clone(), group["dimensions"].clone()));
        for child in group["groups"].as_array().into_iter().flatten() {
            collect(child, &path, out);
        }
    }
    let mut ours = Vec::new();
    collect(&tree, "", &mut ours);
    let theirs: Vec<(String, Value)> = xradar["views"]["auto"]["groups"]
        .as_array()
        .expect("groups")
        .iter()
        .map(|group| {
            (
                group["path"].as_str().unwrap_or("").to_owned(),
                group["dims"].clone(),
            )
        })
        .collect();
    // FM301 gives every sweep the `frequency` dimension, which xradar 0.12
    // leaves out for ODIM (a documented divergence of the core conformance
    // test, design note section 1).
    let sweeps = |groups: &[(String, Value)]| -> Vec<(String, Value)> {
        groups
            .iter()
            .filter(|(path, _)| path.starts_with("/sweep_"))
            .map(|(path, dims)| {
                let mut dims = dims.clone();
                if let Some(map) = dims.as_object_mut() {
                    map.remove("frequency");
                }
                (path.clone(), dims)
            })
            .collect()
    };
    assert_eq!(sweeps(&ours), sweeps(&theirs));
    assert_eq!(sweeps(&ours).len(), 2);
    assert!(ours.iter().any(|(path, _)| path == "/radar_parameters"));
}

fn png_size(path: &Path) -> (u32, u32) {
    let image = png_rgba(path);
    (image.width(), image.height())
}

fn png_rgba(path: &Path) -> image::RgbaImage {
    let bytes = fs::read(path).expect("read PNG");
    image::load_from_memory(&bytes)
        .expect("decode PNG")
        .to_rgba8()
}

/// The opaque pixels of a plan-view render: there are some, every pixel is
/// either transparent or opaque, the corners are transparent, and none lies
/// beyond `range_fraction` of the half-width from the centre (where the far
/// edge of the last gate is drawn).
fn check_plan_view(image: &image::RgbaImage, range_fraction: f64) -> Vec<[u8; 3]> {
    let (width, height) = image.dimensions();
    let centre = (f64::from(width) - 1.0) / 2.0;
    let limit = range_fraction * f64::from(width) / 2.0 + 1.5;
    let mut colours = Vec::new();
    for (x, y, pixel) in image.enumerate_pixels() {
        let [r, g, b, a] = pixel.0;
        assert!(a == 0 || a == 255, "alpha {a} at ({x}, {y})");
        if a == 255 {
            let distance = (f64::from(x) - centre).hypot(f64::from(y) - centre);
            assert!(
                distance <= limit,
                "pixel ({x}, {y}) at {distance:.1} px, limit {limit:.1}"
            );
            colours.push([r, g, b]);
        }
    }
    for (x, y) in [
        (0, 0),
        (width - 1, 0),
        (0, height - 1),
        (width - 1, height - 1),
    ] {
        assert_eq!(image.get_pixel(x, y).0[3], 0, "corner ({x}, {y})");
    }
    assert!(!colours.is_empty(), "no opaque pixel");
    colours
}

/// Whether `colour` lies on the piecewise-linear gradient through `stops`
/// (within 2 levels per channel), as a GR palette of single colours draws.
fn on_gradient(colour: [u8; 3], stops: &[[u8; 3]]) -> bool {
    stops.windows(2).any(|pair| {
        let (a, b) = (pair[0].map(f64::from), pair[1].map(f64::from));
        let c = colour.map(f64::from);
        let ab: Vec<f64> = (0..3).map(|i| b[i] - a[i]).collect();
        let length = ab.iter().map(|d| d * d).sum::<f64>();
        let t = if length == 0.0 {
            0.0
        } else {
            ((0..3).map(|i| (c[i] - a[i]) * ab[i]).sum::<f64>() / length).clamp(0.0, 1.0)
        };
        (0..3).all(|i| (a[i] + t * ab[i] - c[i]).abs() <= 2.0)
    })
}

#[test]
fn render_writes_pngs() {
    let dir = scratch("render");
    let level2 = fixture("l2-ktlx-20240315-000217-trim");
    let png = dir.join("ref.png");
    let output = run([
        OsStr::new("render"),
        level2.as_os_str(),
        OsStr::new("--size"),
        OsStr::new("256"),
        OsStr::new("-o"),
        png.as_os_str(),
    ]);
    assert!(output.status.success(), "{}", stderr(&output));
    assert_eq!(png_size(&png), (256, 256));
    let reflectivity = png_rgba(&png);
    check_plan_view(&reflectivity, 0.94);

    let output = run([
        OsStr::new("render"),
        level2.as_os_str(),
        OsStr::new("--field"),
        OsStr::new("velocity"),
        OsStr::new("--dealias"),
        OsStr::new("--all-sweeps"),
        OsStr::new("--size"),
        OsStr::new("128"),
        OsStr::new("-o"),
        dir.join("vel").as_os_str(),
    ]);
    assert!(output.status.success(), "{}", stderr(&output));
    let written: Vec<_> = fs::read_dir(dir.join("vel"))
        .expect("list")
        .map(|entry| entry.expect("entry").path())
        .collect();
    assert_eq!(written.len(), 1, "only sweep 1 has velocity");
    let velocity = png_rgba(&written[0]);
    check_plan_view(&velocity, 0.94);
    assert!(stdout(&output).contains("VRADDH"), "{}", stdout(&output));

    // A Level III raster product (NCZ, packet 0xBA07) and a GR palette.
    let palette = dir.join("ref.pal");
    fs::write(
        &palette,
        "Product: BR\nUnits: dBZ\nColor: 5 4 233 231\nColor: 30 0 200 0\nColor: 50 255 0 0\nColor: 75 255 255 255\n",
    )
    .expect("write palette");
    let raster = dir.join("ncz.png");
    let output = run([
        OsStr::new("render"),
        fixture("l3-fws-ncz-19950517-2304").as_os_str(),
        OsStr::new("--palette"),
        palette.as_os_str(),
        OsStr::new("-o"),
        raster.as_os_str(),
    ]);
    assert!(output.status.success(), "{}", stderr(&output));
    assert_eq!(png_size(&raster), (1024, 1024));
    let stops = [[4, 233, 231], [0, 200, 0], [255, 0, 0], [255, 255, 255]];
    let raster = png_rgba(&raster);
    let opaque: Vec<[u8; 3]> = raster
        .pixels()
        .filter(|pixel| pixel.0[3] == 255)
        .map(|pixel| [pixel.0[0], pixel.0[1], pixel.0[2]])
        .collect();
    assert!(!opaque.is_empty());
    assert!(opaque.iter().all(|colour| on_gradient(*colour, &stops)));

    let polar = dir.join("pal.png");
    let output = run([
        OsStr::new("render"),
        level2.as_os_str(),
        OsStr::new("--palette"),
        palette.as_os_str(),
        OsStr::new("--size"),
        OsStr::new("200"),
        OsStr::new("-o"),
        polar.as_os_str(),
    ]);
    assert!(output.status.success(), "{}", stderr(&output));
    assert_eq!(png_size(&polar), (200, 200));
    let colours = check_plan_view(&png_rgba(&polar), 0.94);
    assert!(
        colours.iter().all(|colour| on_gradient(*colour, &stops)),
        "a colour off the palette"
    );
    // The palette changed the colours: some are in no pixel of the render
    // with the default table.
    assert!(
        colours
            .iter()
            .any(|c| !reflectivity.pixels().any(|p| p.0[..3] == c[..]))
    );
    fs::remove_dir_all(&dir).expect("clean up");
}

#[test]
fn validate_passes_radar_files_and_fails_other_files() {
    let files = [
        fixture("l2-ktlx-20240315-000217-trim"),
        fixture(ESPDG),
        fixture("l3-byx-n0q-20150124-2106"),
        fixture("l2chunk-kiwa-307-20260917-003629-001-s"),
    ];
    let mut args = vec![OsStr::new("validate"), OsStr::new("--json")];
    args.extend(files.iter().map(|path| path.as_os_str()));
    let report = json(&run(&args));
    assert_eq!(report["failed"], 0, "{report}");
    assert_eq!(report["files"].as_array().map(Vec::len), Some(4));

    let listing = fixture("polling-ndswc-kxwa-dir-list-20260925");
    let output = run([OsStr::new("validate"), listing.as_os_str()]);
    assert_eq!(output.status.code(), Some(1));
    assert!(stdout(&output).contains("FAIL"), "{}", stdout(&output));
}

#[test]
fn bench_times_decodes() {
    let report = json(&run([
        OsStr::new("bench"),
        OsStr::new("--json"),
        OsStr::new("-n"),
        OsStr::new("2"),
        OsStr::new("--warmup"),
        OsStr::new("0"),
        OsStr::new("--threads"),
        OsStr::new("1"),
        fixture("l2-ktlx-20240315-000217-trim").as_os_str(),
    ]));
    assert_eq!(report["threads"], 1);
    let result = &report["results"][0];
    assert_eq!(result["rays"], 960);
    assert_eq!(result["iterations"], 2);
    assert!(result["median_ms"].as_f64().unwrap_or(0.0) > 0.0);
}

#[test]
fn convert_writes_every_format_and_publish_a_polling_directory() {
    let dir = scratch("convert");
    let espdg = fixture(ESPDG);
    let source = json(&run([
        OsStr::new("info"),
        OsStr::new("--json"),
        fixture(ESPDG).as_os_str(),
    ]));
    let source = &source["volumes"][0];
    let rays: Vec<&Value> = source["sweeps"]
        .as_array()
        .expect("sweeps")
        .iter()
        .map(|sweep| &sweep["rays"])
        .collect();

    // Each writer's file reads back with the source's sweeps and rays.
    for (format, name, read_as) in [
        ("level2", "out.ar2v", "NEXRAD Level II"),
        ("cfradial1", "out.cf1.nc", "CfRadial"),
        ("odim", "out.h5", "ODIM_H5"),
        ("fm301", "out.fm301.nc", "CfRadial"),
    ] {
        let out = dir.join(name);
        let mut args = vec![
            OsStr::new("convert"),
            espdg.as_os_str(),
            OsStr::new("--to"),
            OsStr::new(format),
            OsStr::new("-o"),
            out.as_os_str(),
        ];
        if format == "level2" {
            args.extend([OsStr::new("--site"), OsStr::new("SPDG")]);
        }
        let output = run(&args);
        assert!(output.status.success(), "{format}: {}", stderr(&output));
        let report = json(&run([
            OsStr::new("info"),
            OsStr::new("--json"),
            out.as_os_str(),
        ]));
        assert!(
            report["format"]
                .as_str()
                .is_some_and(|text| text.starts_with(read_as)),
            "{format}: {report}"
        );
        let volume = &report["volumes"][0];
        assert_eq!(volume["sweep_count"], source["sweep_count"], "{format}");
        let read_rays: Vec<&Value> = volume["sweeps"]
            .as_array()
            .expect("sweeps")
            .iter()
            .map(|sweep| &sweep["rays"])
            .collect();
        assert_eq!(read_rays, rays, "{format}");
        if format == "level2" {
            assert_eq!(volume["site"], "SPDG");
        }
    }

    // Real-time chunks: the S, I and E files of one volume, which
    // concatenated are an Archive II file.
    let chunks = dir.join("chunks");
    let output = run([
        OsStr::new("convert"),
        fixture(ESPDG).as_os_str(),
        OsStr::new("--to"),
        OsStr::new("level2"),
        OsStr::new("--chunks"),
        OsStr::new("--site"),
        OsStr::new("SPDG"),
        OsStr::new("-o"),
        chunks.as_os_str(),
    ]);
    assert!(output.status.success(), "{}", stderr(&output));
    let mut files: Vec<PathBuf> = walk(&chunks);
    files.sort();
    assert!(files.len() >= 2, "{files:?}");
    let names: Vec<String> = files
        .iter()
        .filter_map(|path| path.file_name())
        .map(|name| name.to_string_lossy().into_owned())
        .collect();
    assert!(
        names.first().is_some_and(|name| name.ends_with("-001-S")),
        "{names:?}"
    );
    assert!(
        names.last().is_some_and(|name| name.ends_with("-E")),
        "{names:?}"
    );
    let mut archive = Vec::new();
    for file in &files {
        archive.extend(fs::read(file).expect("chunk"));
    }
    let joined = dir.join("joined.ar2v");
    fs::write(&joined, archive).expect("write joined chunks");
    let report = json(&run([
        OsStr::new("info"),
        OsStr::new("--json"),
        joined.as_os_str(),
    ]));
    assert_eq!(report["volumes"][0]["sweep_count"], source["sweep_count"]);

    // publish: a polling directory in the GRLevelX layout.
    let root = dir.join("polling");
    for keep in ["2", "1"] {
        let output = run([
            OsStr::new("publish"),
            fixture(ESPDG).as_os_str(),
            OsStr::new("--dir"),
            root.as_os_str(),
            OsStr::new("--site"),
            OsStr::new("SPDG"),
            OsStr::new("--keep"),
            OsStr::new(keep),
        ]);
        assert!(output.status.success(), "{}", stderr(&output));
    }
    for file in ["config.cfg", "grlevel2.cfg"] {
        let text = fs::read_to_string(root.join(file)).expect("site list");
        assert_eq!(text, "Site: SPDG\r\n", "{file}");
    }
    let listing = fs::read_to_string(root.join("SPDG/dir.list")).expect("dir.list");
    let lines: Vec<&str> = listing.split_terminator("\r\n").collect();
    assert_eq!(lines.len(), 1, "{listing:?}");
    let (size, name) = lines[0].split_once(' ').expect("<size> <name>");
    assert!(
        name.starts_with("SPDG_2026") && name.ends_with(".ar2v"),
        "{name}"
    );
    let published = root.join("SPDG").join(name);
    assert_eq!(
        size.parse::<u64>().ok(),
        fs::metadata(&published).ok().map(|m| m.len())
    );
    let report = json(&run([
        OsStr::new("info"),
        OsStr::new("--json"),
        published.as_os_str(),
    ]));
    assert_eq!(report["volumes"][0]["site"], "SPDG");
    fs::remove_dir_all(&dir).expect("clean up");
}

/// Every file under `dir`, at any depth.
fn walk(dir: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    for entry in fs::read_dir(dir).expect("read dir").flatten() {
        let path = entry.path();
        if path.is_dir() {
            files.extend(walk(&path));
        } else {
            files.push(path);
        }
    }
    files
}

fn http_get(address: &str, path: &str) -> (String, Vec<u8>) {
    let mut stream = TcpStream::connect(address).expect("connect");
    write!(stream, "GET {path} HTTP/1.1\r\nHost: {address}\r\n\r\n").expect("send request");
    let mut response = Vec::new();
    stream.read_to_end(&mut response).expect("read response");
    let split = response
        .windows(4)
        .position(|window| window == b"\r\n\r\n")
        .expect("header end");
    let head = String::from_utf8_lossy(&response[..split]).into_owned();
    (head, response[split + 4..].to_vec())
}

#[test]
fn serve_answers_like_a_polling_server() {
    let dir = scratch("serve");
    let listing = fixture("polling-ndswc-kxwa-dir-list-20260925");
    fs::create_dir_all(dir.join("KXWA")).expect("site folder");
    fs::copy(&listing, dir.join("KXWA/dir.list")).expect("copy listing");

    let mut child = Command::new(env!("CARGO_BIN_EXE_recast-radar"))
        .args([
            OsStr::new("serve"),
            dir.as_os_str(),
            OsStr::new("--bind"),
            OsStr::new("127.0.0.1:0"),
            OsStr::new("--max-requests"),
            OsStr::new("3"),
        ])
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .expect("start server");
    let mut line = String::new();
    BufReader::new(child.stdout.take().expect("stdout"))
        .read_line(&mut line)
        .expect("server banner");
    let address = line
        .split("http://")
        .nth(1)
        .and_then(|rest| rest.split('/').next())
        .expect("address in banner")
        .to_owned();

    let (head, body) = http_get(&address, "/KXWA/dir.list");
    assert!(head.starts_with("HTTP/1.1 200"), "{head}");
    assert_eq!(body, fs::read(&listing).expect("read listing"));
    let (head, body) = http_get(&address, "/");
    assert!(head.starts_with("HTTP/1.1 200"), "{head}");
    assert!(String::from_utf8_lossy(&body).contains("KXWA/"));
    let (head, _) = http_get(&address, "/../Cargo.toml");
    assert!(
        head.starts_with("HTTP/1.1 403") || head.starts_with("HTTP/1.1 404"),
        "{head}"
    );

    let status = child.wait().expect("server exits after 3 requests");
    assert!(status.success());
    fs::remove_dir_all(&dir).expect("clean up");
}

#[cfg(feature = "net")]
#[test]
fn fetch_lists_providers_and_sites_offline() {
    let output = run(["fetch", "intl"]);
    assert!(output.status.success(), "{}", stderr(&output));
    let text = stdout(&output);
    for provider in ["smhi", "dwd", "fmi", "jma"] {
        assert!(text.contains(provider), "{provider}: {text}");
    }
    let output = run(["fetch", "intl", "smhi", "--list-sites"]);
    assert!(output.status.success(), "{}", stderr(&output));
    assert!(!stdout(&output).trim().is_empty());

    let sites = json(&run(["fetch", "sites", "--json"]));
    let ktlx = sites
        .as_array()
        .expect("sites")
        .iter()
        .find(|site| site["id"] == "KTLX")
        .expect("KTLX in the embedded table");
    assert!((ktlx["latitude_deg"].as_f64().unwrap_or(0.0) - 35.33).abs() < 0.05);

    let output = run(["fetch", "intl", "nope"]);
    assert_eq!(output.status.code(), Some(2));

    // --date needs a provider with an archive; the refusal names them, and
    // comes before any request.
    let output = run(["fetch", "intl", "dmi", "dkste", "--date", "2026-06-12"]);
    assert_eq!(output.status.code(), Some(2), "{}", stderr(&output));
    assert!(
        stderr(&output).contains("has no archive"),
        "{}",
        stderr(&output)
    );
    assert!(stderr(&output).contains("smhi"), "{}", stderr(&output));
    let output = run(["fetch", "intl", "smhi", "--time", "12:00", "hemse"]);
    assert_eq!(output.status.code(), Some(2), "{}", stderr(&output));
}

#[cfg(not(feature = "net"))]
#[test]
fn fetch_needs_the_net_feature() {
    let output = run(["fetch", "sites"]);
    assert_eq!(output.status.code(), Some(3), "{}", stderr(&output));
    assert!(stderr(&output).contains("net"), "{}", stderr(&output));
}
