[package]
name = "recast-radar-map"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rayon.workspace = true
recast-radar-core = { path = "../recast-radar-core" }
recast-radar-correct = { path = "../recast-radar-correct" }
recast-radar-filters = { path = "../recast-radar-filters" }

[dev-dependencies]
recast-radar-io-cfradial = { path = "../recast-radar-io-cfradial" }

[lints]
workspace = true
